### ISSUE TITLE
 - להציג תוצאות חיפוש מכרזים לפי תאריך בסדר יורד

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#101]
@akariv  האם אנחנו מציגים כרגע תוצאות רק מאותו סשרד שהשירות שייך אליו?

**Comment by akariv** [comment]
כן.

לגבי השאר - כבר דיברנו על זה כאן

https://github.com/hasadna/social-procurement/issues/78#issuecomment-831346345

**Comment by niryariv** [comment]
״הסינון הוא לפי הרלוונטיות לחיפוש - כל מיון אחר יתן תוצאות חיפוש פחות טובות״
