### ISSUE TITLE
טקסט חדש לסימן שאלה באופציות

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#102]

**Comment by ShiraTza** [comment]
מספר האופציות  = מספר האופציות הקיימות.
סך משך האופציות = סך משך השנים באופציות. למשל, אופציות של 2+3, משך הזמן
סה"כ הוא 5 שנים.

‫בתאריך יום ג׳, 18 במאי 2021 ב-11:27 מאת ‪Nir Yariv‬‏ <‪
***@***.***‬‏>:‬
