### ISSUE TITLE
במקום שבו מופיע ״תקציב״ בממשק האתר, להוסיף הבהרה

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#104]
״תקציב שניתן על ידי המשרד בלבד, לא כולל השתתפות רשויות או את גובה התרומה של הגוף השותף לממשלה, במיזמים משותפים״

**Comment by akariv** [comment]
לא הבנתי איפה

**Comment by niryariv** [comment]
מוחק

**Comment by akariv** [comment]
מה ההבדל בין זה לבין 103?

**Comment by niryariv** [comment]
משימה #103 היתה לגבי ממשק הזנה. את זה יצרתי לעצמי ושמתי בבקלוג לקראת העיצוב של ממשק הצפיה. כשראיתי את ההערה שלך הנחתי ששכחתי לשים את הצלום מסך עם המיקום.. תתעלם מהמשימה הזו, כרגע היא אלי

**Comment by morchickit** [comment]
אני משערת שזה לא רלוונטי יותר? שאני אסגור?

**Comment by akariv** [comment]
באמת שלא יודע, זו היתה משימה של ניר

**Comment by morchickit** [comment]
סוגרת בינתיים.
