### ISSUE TITLE
לא לחייב הזנת תקציב טרום-2017

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#106]
למשל בנקרה הנ״ל - לאפשר שמירה כשירות שהושלם

![Screen Shot 2021-05-20 at 13 26 59](https://user-images.githubusercontent.com/1771/118963381-1208b100-b96f-11eb-9d02-4823b755f5cc.png)

**Comment by akariv** [comment]
פשוט מוחקים את השורות איפה שאין תקציב
