### ISSUE TITLE
תיקון להיררכיה

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#107]
בשירותים שאין להם אגף, לא לשים ישירות תחת מנהל אלא לשיך לאגף ״אחר״

(דוגמא: משרד מדע תחת מנהל מדע וטכנולוגיה)

**Comment by akariv** [comment]
מה השינוי הנדרש פה? פשוט לערוך את ההיררכיה ולתקן את השירותים

**Comment by niryariv** [comment]
זה לא יוצר בעיה במקרה של ייבוא מידע מקובץ (לפני הייבוא של קטלוג רווחה בדקת מולי אם נעשה שינוי בהיררכיות)?

**Comment by akariv** [comment]
מניח שסיימנו עם הייבוא, לא?

**Comment by akariv** [comment]
בכל מקרה, אם נייבא שוב נוודא שהמידע בקובץ המקור תקין.

**Comment by morchickit** [comment]
אדם שאני אתקן ידנית פה?

**Comment by morchickit** [comment]
@akariv שנסגור את זה?

**Comment by akariv** [comment]
כן
