### ISSUE TITLE
הזנת מידע לפי שנים

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#108]
- [x] מקומות שבהם ממלאים מידע לפי שנים: מוטבים, תקציב בפועל / תקציב מאושר - לאפשר רק הזנת מידע מ 2017 והלאה, ולחייב מילוי כל השנים הנ״ל

- [x] לוודא שקיים מידע לכל השנים 2017-2020 (שירות שאינו פעיל לא צריך להיות במערכת)

(מבטל את #106)

- [x] כשמייבאים תקנה, לייבא רק שורות מ 2017 והלאה (מבטל את #67)

**Comment by akariv** [comment]
לא הבנתי למה לא לאפשר הזנת מידע מוקדם יותר אם ישנו

**Comment by niryariv** [comment]
ההנחיה שהמשתמשות קיבלו היא להזין מידע מ 2017 והלאה, השנים הנוספות רק מעמיסות על הממשק שלא לצורך - הן לא אמורות למלא אותן

**Comment by akariv** [comment]
ok

**Comment by akariv** [comment]
בוצע עבור התקציב

**Comment by niryariv** [comment]
מה לגבי תקנות (בשביל #67) ומוטבים? 

(במוטבים אפשר להסתפק בחיוב הזנת 2017-2021, אין העמסה על הממשק אז אין מניעה שיזינו שנה קודמת אם הם רוצים

**Comment by akariv** [comment]
אם השירות לא היה קיים ב-2017 אז אין מה להזין (בשונה ממוטבים ותקציבים שאפשר
להכניס ״0״)
עבור המוטבים בבקשה תפתח משימה נפרדת כי למיטב הבנתי הדחיפות של זה נמוכה יותר.
