### ISSUE TITLE
תוספת לטקסט תחת ״תקציב השירות״

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#109]
> במידה והתקציב בתקנה משויך כולו לשירות הספציפי ולא כולל שירותים נוספים, יש להשתמש בנתוני התקציב המאושר ותקציב הביצוע בפועל כפי שמופיעים בספר התקציב (ראו מצד שמאל). במצב בו בתקנה כלולים מספר שירותים, הקפידו להכניס את התקציב המאושר ותקציב הביצוע בפועל, הרלוונטיים **רק לשירות הספציפי**.

**Comment by ShiraTza** [comment]
שלחתי בווטסאפ לניר.
אם לא מופיע, זה התקציב - להוסיף ולא במקום מה שמופיע

במידה והתקציב בתקנה משויך כולו לשירות הספציפי ולא כולל שירותים נוספים, יש
להשתמש בנתוני התקציב המאושר ותקציב הביצוע בפועל כפי שמופיעים בספר התקציב
(ראו מצד שמאל). במצב בו בתקנה כלולים מספר שירותים, הקפידו להכניס את התקציב
המאושר ותקציב הביצוע בפועל, הרלוונטיים רק לשירות הספציפי.

‫בתאריך יום ה׳, 20 במאי 2021 ב-16:34 מאת ‪Nir Yariv‬‏ <‪
***@***.***‬‏>:‬

**Comment by akariv** [comment]
@ShiraTza 
המשימה הזו כבר בוצעה ונסגרה... האם נדרשים שינויים?

**Comment by ShiraTza** [comment]
לא, פשוט עברתי על מה שהגיע אלי. אח"כ ראיתי שהמשימה נסגרה. אחלה תודה

‫בתאריך יום ה׳, 27 במאי 2021 ב-12:32 מאת ‪Adam Kariv‬‏ <‪
***@***.***‬‏>:‬
