### ISSUE TITLE
לוודא שמשתמשי רכש חברתי לא רואים את סרגל הניווט (מלבד קישורים למסך הראשי + התנתקות) 

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#11]

**Comment by akariv** [comment]
בוצע

**Comment by niryariv** [comment]
עדיין מקבל קישורים ל״לוח הבקרה״ ו״שרותים חברתיים״, אני חושב שאחרי מימוש #14 אפשר להוריד אותם ולהסתפק בקישור לדף הבית / התנתקות. 

 בנוסף נעלה למקום בו הסרגל כיום את שם המשתמש ולוגו המשרד שמקשר לרשימת הסעיפים כמו שמתואר ב #14

**Comment by akariv** [comment]
לוח הבקרה הוא דף הבית, שירותים חברתיים הוא רשימת כל השירותים החברתיים.
גם לאחר מימוש #14 יש ערך ביכולת לצפות במידע הקיים במערכת שלא דרך המשקפיים
של ״מה המשימות שאני צריך לעשות״.

**Comment by niryariv** [comment]
אבל מימוש #14 נותן למשתמש לסקור את כל השרותים החברתיים של המשרד בדף הבית..

**Comment by akariv** [comment]
כן, בחלוקה של דורש עבודה / מוכן ולא בחלוקה כוללת של משרד / אגף / מחלקה

**Comment by niryariv** [comment]
למה שלא נוסיף את החלוקות האלו באותו עמוד בית?
