### ISSUE TITLE
ממשק צפיה סבב ראשון 

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#110]
לשוניות: שירותים, תקציב, מפעילים

בשלב זה תוכן רק ללשונית שירותים. 

רמת מקרו + משרד

בתוך הלשונית:
* פילוח לפי משרדים (כמות שירותים, פיי + רצף זמן)
* פילוח לפי קבוצת גיל, אוכלוסיה, תחום התערבות, אופן התערבות 
* פילוח עם פטור / מכרז / גם וגם
רשימת שירותים לפי הפילוח המוצג

**Comment by morchickit** [comment]
@akariv - can I close this?

**Comment by akariv** [comment]
Yes
