### ISSUE TITLE
 התראות בהזנת תקציב

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#111]
להראות התראה (לא ברמה שמונע סיום עבודה, רק כאזהרה):

- [ ] במקרה שתקציב מאושר גבוה מתקציב בש״ח
`שימו לב, התקציב המאושר שהזנתם - גבוה מהתקציב המאושר בתקנה כפי שפורסם בספר התקציב (ראו מצד שמאל). בדקו שוב אם הסכום מדויק`
- [ ] במקרה שתקציב בפועל גבוה מביצוע תקציב
`שימו לב, תקציב הביצוע בפועל שהזנתם - גבוה מתקציב הביצוע בתקנה כפי שפורסם בספר התקציב (ראו מצד שמאל). בדקו שוב אם הסכום מדויק`

**Comment by akariv** [comment]
יכנס אחרי ממשק הצפיה

**Comment by niryariv** [comment]
cc @ShiraTza

**Comment by niryariv** [comment]
אני מקבל על תקציב בפועל > ביצוע תקציב את ההתראה של תקציב מאושר > תקציב  בש״ח
![Screen Shot 2021-06-03 at 9 09 04](https://user-images.githubusercontent.com/1771/120595629-5efa8600-c44b-11eb-9cfa-d44aab221b3e.png)

**Comment by akariv** [comment]
טעות קופי פייסט
