### ISSUE TITLE
נתונים מספר התקציב לא מדוקים

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#112]
בתקנות שהמובילות עבדו עליהם לפני שעשינו את השינוי בממשק תקנה תקציבית, אנחנו מזהים סכומים לא נכונים. 

[דוגמא כאן:](https://data-input.obudget.org/he/datarecords/social_service/hpqt-khvmry-hdrkh-vbytsv-hdrkh-ltlmydy-hkhynvk-hmmlkty-dty-bmsgrt-tknyt-hrmb-m-ltlmyd)

![Screen Shot 2021-05-25 at 10 14 42](https://user-images.githubusercontent.com/1771/119455192-0851c580-bd42-11eb-8883-ebaa115af288.png)

תקציב תקנה [20.67.03.03](https://next.obudget.org/i/budget/0020670303/2020?li=0&theme=budgetkey) הוא 11.8 מליון, בממשק מופיע 2.9

[(דוגמא נוספת כאן)](https://data-input.obudget.org/he/datarecords/social_service/shyqvm-nky-npsh-bqhylh-shyrvty-shyqvm-bdyvr-hvstlym)

**Comment by akariv** [comment]
מניח שהוזן בעבר התקציב הזה ידנית, אולם הוא לא אמור להופיע בטבלת ״נתונים מספר התקציב״

**Comment by niryariv** [comment]
cc @ShiraTza

**Comment by akariv** [comment]
אחרי התיקון

![IMG_20210525_170241.jpg](https://user-images.githubusercontent.com/265333/119511474-1c65e900-bd7b-11eb-9a6f-66f10ffc3856.jpg)

**Comment by niryariv** [comment]
ראיתי, אחרי ריפרש :)
