### ISSUE TITLE
טיפול בחוזה אחיד

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#115]
בלשונית מכרזים, צ׳קבוקס ״השירות לא ניתן מכוח מכרז או פטור, אלא בהסכם חוזי היסטורי אחר״ - אם הוא מסומן, לא מחייבים הזנת מכרזים/פטורים

@ShiraTza תעביר נוסח מדויק

**Comment by ShiraTza** [comment]
הניסוח -
השירות לא ניתן מכוח מכרז או פטור, אלא בהסכם חוזי אחר

‫בתאריך יום ה׳, 27 במאי 2021 ב-14:17 מאת ‪Nir Yariv‬‏ <‪
***@***.***‬‏>:‬

**Comment by ShiraTza** [comment]
מתקנת את הניסוח -
השירות לא ניתן מכוח מכרז או פטור, אלא בהסכם חוזי היסטורי אחר

‫בתאריך יום ה׳, 27 במאי 2021 ב-14:36 מאת ‪Shira Tzachor‬‏ <‪
***@***.***‬‏>:‬
