### ISSUE TITLE
דף הבית של משתמש רכש חברתי

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#12]
1. פרטי המשתמש (שם, משרד)
2. רשימת שרותים חברתיים רלבנטים
3. ליד כל שרות, חיווי לגבי הנתונים שמולאו לכל שנה (ריק, מלא חלקית, מלא - ״מלא״ זה דגל שהמשתמש מסמן כשסיים לעבוד על סעיף)

**Comment by akariv** [comment]
בוצע

**Comment by niryariv** [comment]
(בעקרון מיזוג התוכן של דפי לוח הבקרה ושרותים חברתיים)

**Comment by akariv** [comment]
@niryariv וכל להפרט לגבי סעיף 3 - למה בדיוק אתה מתכוון?

**Comment by niryariv** [comment]
בגדול לזה, בוצע:
![Screen Shot 2021-04-12 at 14 27 19](https://user-images.githubusercontent.com/1771/114387509-32d52e00-9b9b-11eb-93c0-0c09af75fbb4.png)

**Comment by niryariv** [comment]
[הקישור הקודם לדף שירותים חברתיים](https://data-input.obudget.org/he/datarecords/social_service) נראה עכשיו כך - יש משתמשים שניגשים ישירות לשם, מציע לשנות כך שיעביר את המשתמש לדף הראשי או פשוט יחזיר 404

![Screen Shot 2021-04-14 at 12 38 38](https://user-images.githubusercontent.com/1771/114689430-5aa0cf00-9d1e-11eb-9c40-414c919e0889.png)
