### ISSUE TITLE
סימון שירות כלא פעיל

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#121]
אנחנו רוצים להוסיף יכולת להגדיר שירות כלא פעיל - להבדיל מפשוט למחוק אותו. הצעה למימוש:

1. תחת הלשונית של תקנה תקציבית, תחת הטבלה המרכזית ״תקציב השירות״, במצב שבו השנה האחרונה להזנת תקציב ריקה או על 0, מופיע כפתור ״סמן שירות כלא פעיל החל משנה []״ 
2. כשהמשתמש לוחץ על הכפתר, הוא מתחלף בהודעה ״שירות זה אינו פעיל משנה []״ שלידה כפתור ״סמן כפעיל״
3. לחיצה על כפתור ״סמן כפעיל״ מוחקת את ההודעה, מחזירה את כפתור ״סמן כלא פעיל״ והופכת את השירות חזרה לפעיל
4. שירות שהוגדר לא פעיל מופיע בלוח בקרה בפונט אפור, עם סטטוס אדום ״לא פעיל״.
5. כדי למנוע תקלות, לא ניתן לשמור עריכה בשירות בסטטוס לא פעיל. פס הכפתורים התחתון מקבל רקע אפור ובמקום כפתורי השמירה יש כפתור אחד ״שירות לא פעיל - חזרה ללוח הבקרה״ (כפתור מחיקה נשאר כמו שהוא)

@akariv דעתך?

**Comment by akariv** [comment]
הכי פשוט זה לאחד את זה עם מנגנון המחיקה - במקום מחיקה ו״מחיקה סופית״ (כמו
שקיים היום) יהיה ״סימון כלא פעיל״ ו״מחיקה״.

מה דעתך?

**Comment by niryariv** [comment]
אין בעיה כל זמן שיש דרך חזרה מהסטטוס. אני חושב שכדאי לוהסיף גם בדיקה (לא בטוח אם ברמת ההתראה או מניעת הפעולה) שלא הוזן תקציב לשנה שבה מסומן כלא פעיל.

**Comment by akariv** [comment]
אני לא חושב שזה תמיד יהיה מעבר חד כמו שאתה מתאר את זה... עשוי להיות שימשיך
להיות תקציב למרות שהמשרד כבר לא מפעיל את השירות.

**Comment by niryariv** [comment]
👍
