### ISSUE TITLE
סימון מפעיל כלא פעיל

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#122]
בפרטי מפעיל, לשנות את רשימת הבחירה ״קשור / לא קשור / כנראה קשור״ ל ״קשור ופעיל / קשור אך לא פעיל / לא קשור / כנראה קשור״

**Comment by akariv** [comment]
מציע להפריד בין שני המאפיינים הלא קשורים האלה (האם פעיל והאם קשור)

**Comment by niryariv** [comment]
מקובל, כמו כן צריך להסיק שנות פעילות (לפי השנה שקושר / השנה שסומן כלא פעיל?)

**Comment by niryariv** [comment]
עלה לאתר? אני לא רואה איך מסמנים

**Comment by akariv** [comment]
לוקח כמה דקות מסגירת הטיקט ועד לדיפלוי
