### ISSUE TITLE
לאפשר סוגי מוטבים

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#123]
כיום מספר המוטבים מתייחס לאנשים. קיים צורך להגניס סוג של ״רשויות״ - כלומר המשתמש יסמן 3 כשהכוונה ״3 רשויות. 

ניישם בתוך רשימת בחירה בממשק המוטבים, כשברירת המחדל היא ״אנשים״. הבחירה משפיעה על כל הנתונים לכל השנים.

זה מין הסתם יפתח את הדלת לעוד סוגים - בתי ספר וכו׳ - כך שנרצה את רשימת הסוגים ניתנת לעריכה, כמו תחומים וכו׳.

**Comment by niryariv** [comment]
כיום ברירת המחדל ריקה - צריך להוריד אפשרות ריקה מרשימת הבחירה ולאפשר לאדמין לקבוע את ברירת המחדל (שגם תופיע ראשונה ברשימה).

  אפשר פשוט לקבוע שהפריט הראשון ברשימה הוא ברירת המחדל (ולהוסיף איזה חיווי לגבי זה לאדמין)

**Comment by niryariv** [comment]
בשירותים שכבר מולאו, סוג המוטב כרגע נשמר כ״אנשים״ או שצריך לחזור ולערוך בממשק?

**Comment by akariv** [comment]
צריך לחזור ולערוך בממשק אבל זה משהו שאפשר לעשות אח״כ אוטומטית.

אדם

**Comment by niryariv** [comment]
ממשיך ב #124
