### ISSUE TITLE
מכרזים חסרים בדוחות רכש

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#126]
אדם העביר למנהל הרכש רשימה של מכרזים שלא מופיעים בדוחות שלהם

יוני מעדכן - מנהל הרכש מודע לבעיה, הוא בבדיקה אצל מרכב"ה. המנהל צריך לעדכן אותנו לגבי התקדמות.

שירה בקשר מול המנהל.

**Comment by morchickit** [comment]
@akariv אתה זוכר משהו? 
האם אפשר למחוק את זה אחרי השיחות עם מרכב"ה השבוע?

**Comment by akariv** [comment]
לא ידוע לי אם נפתר אבל בכל מקרה אין לנו מה לעשות כאן

**Comment by morchickit** [comment]
אז אני סוגרת את זה.
