### ISSUE TITLE
ארגון המידע ההיסטורי 

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#127]
הפרדה בין מידע עבר שאינו פעיל ובין המידע על הדברים הפעילים. 
יענה על סיפורי המשתמשים הבאים -

- כיוזר של האתר אני רוצה לדעת את המידע על שירות היום כדי שאני אדע מה פעיל
- כיוזר של האתר אני רוצה לדעת מה היה בעבר כדי שאבין מגמות
- כיוזר של האתר אני אני רוצה שהגרפים ישקפו מידע להיום כדי שיהיה לי קל להבין 
- כיוזר של האתר אני רוצה לדעת מה קורה על מפעיל היום לעומת העבר כדי לעשות ניתוח שוק
- כמזין מידע אני רוצה אפשרות לסמן שמכרז/מפעיל הוא לא פעיל 
-  כמזין מידע אני רוצה שתוקף המכרז יסמן לי האם מכרז לקראת סיום כדי שאני אוכל לוודא האם הוא אכן הסתיים בפועל

"

**Comment by morchickit** [comment]
משימות באפיק זה: 

- [x] #128 
- [x] #129

**Comment by akariv** [comment]
ראי הערה ב #128

**Comment by morchickit** [comment]
All done
