### ISSUE TITLE
הוספת שדה "מכרז הסתיים" במכרזים

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#128]
חלק מאפיק #127 
הרציונל - להראות שמכרז הגיעו לסיומו. 
למכרז יהיו שני מצבים - פעיל והסתיים. 
שדה זה ימולא על ידי המובילים ויהיה כברירת מחדל כפעיל.

**Comment by morchickit** [comment]
בעתיד אולי יהיה שווה להוסיף עוד אפשרויות לשדה כמו "הוארך", אבל לגרסא זו ננסה רק את שתי האפשרויות למעלה. כמו כן, בעתיד אולי נוכל לצרף תאריך של מתי יסתיים, אבל כרגע לפי המידע הקיים לא תמיד ידוע.

**Comment by akariv** [comment]
צריך לתמחר בנפרד את התכולה הזו שכן התמחור הנוכחי מניח שאין שינויים במערכת
ההזנה.

**Comment by morchickit** [comment]
כן, הבינותי, פשוט אני לא רואה שום לוגיקה אחרת שכן אפילו במנהל הרכש הם לא יודעים מתי מכרז מסתיים, אלא אם כן יש הזמנה שננעלה, וזו מצויה במודול הלוגיסטי וגם לא תמיד זה אומר שמכרז הסתיים

**Comment by akariv** [comment]
אוקיי, אז אתמחר ונעביר לאישור לפני המימוש.

**Comment by morchickit** [comment]
בוא נוסיף את זה כשאלה למרכב"ה שבוע הבא לפני תמחור?

**Comment by akariv** [comment]
אפשר

**Comment by morchickit** [comment]
טוב, אז שאלנו במרכב"ה, והם אמרו שמכרז נסגר לפי הקניינים והחשבים. עכשיו השאלה - האם אנחנו צריכים להוסיף את זה ככפתור או פשוט להניח שאם לא הוספנו אופציות אז המכרז לא הסתיים. @akariv

**Comment by akariv** [comment]
אני חושב שלהוסיף שדה מידע נוסף שעלול להיות בסתירה עם מידע שכבר קיים (תוקף + אופציות <> פעיל / לא פעיל) זה מתכון לצרות.
הנחת היסוד היא שמכרז מפסיק להיות פעיל אחרי התוקף שלו + משך האופציות. אם זה לא נכון, אז שיתקנו את המידע הזה (תוקף ואופציות) או שנמחק את השדות האלה ונשאיר רק את השדה ״פעיל/לא פעיל״ שאותו אנשי הרכש יצטרכו לעדכן בתדירות גבוהה.

**Comment by morchickit** [comment]
אני תוהה אם אולי ב- UI נוכל להראות פעיל לא פעיל לפי תוק, ואופציות, אבל זה נושא אחר. אני אסגור את זה פה בינתיים
