### ISSUE TITLE
התראה שמכרז עומד להסתיים 

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#129]
אם תאריך תוקף של מכרז הוא לפני השנה הנוכחית והמזין אמר שהוא פעיל ולא מלא אופציות הארכה, התראה תינתן למשתמש לבדוק האם המכרז באמת פעיל.

**Comment by morchickit** [comment]
תחת #127

**Comment by morchickit** [comment]
בתיאוריה מכרז עם תאריך סיום בלי הארכה אמור להיות מכרז עבר, אבל זה גם לא באמת נכון.

**Comment by akariv** [comment]
איפה המזין מציין אם מכרז הוא פעיל או לא? האם יש הגדרה מדויקת (מבחינת אנשי הרכש) של מה זה בכלל ״מכרז פעיל״?
למה זה לא נכון ש״מכרז עם תאריך סיום בלי הארכה אמור להיות מכרז עבר״?

**Comment by morchickit** [comment]
אני סוגרת את זה כי פתחתי אישיו יותר עדכני ב #146
