### ISSUE TITLE
הוספת שדה לתיעוד התהליך

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#13]
מיועד למשתמש כדי לתעד מהיכן השיג את המידע

נראה לי שצריכים להיות לפחות שני שדות כאלו - אחד כללי (הרי המשתמשים לא יתעדו בכל שירות ״שאלתי את שולה״) והשני ספציפי לסעיף הנוכחי, כי אולי יש מידע רלבנטי לסעיף. כרגע נתחיל בשדה כללי ונחכה למשוב משתמשים

**Comment by akariv** [comment]
הסעיף הכללי אמור להיות על איזו ישות?

**Comment by niryariv** [comment]
נראה לי כללי פר משרד. 

במחשבה שניה אולי אנחנו רוצים טקסט ״תיעוד״ לכל שדה בטופס, ואז אפשרות בתוך שירות ספציפי להוסיף טקסט לשדה בהקשר של השירות הזה

**Comment by niryariv** [comment]
(צריך לבדוק אם נכון יותר לעשות את זה פר מינהל/חטיבה - אני אשאל את שירה)

**Comment by akariv** [comment]
בוצע

**Comment by niryariv** [comment]
1. שנה ״סטטוס״ ל״תיעוד מקורות המידע״
2. שנה ״הערות כלליות (לא לפרסום):״ ל״(מידע זה מיועד למנהלי/ות הרכש שיזינו מידע בעתיד. הוא לא יוצג בממשק המשתמש הרגיל)״
 
![Screen Shot 2021-01-06 at 12 39 51](https://user-images.githubusercontent.com/1771/103759388-5167de00-501c-11eb-9d04-fe7a7643050b.png)

**Comment by akariv** [comment]
סטטוס גם כולל את האינדיקציה אם הסתיימה העבודה או לא, אולי אפשר למצוא שם
יותר מתאים לכותרת.

**Comment by niryariv** [comment]
אני חושב שכדאי להפריד את האינדיקציה הזו לממשק אחר - נניח כפתור שהמשתמש לוחץ
עליו - נרצה להיות מסוגלים לסנן במקומות שונים לפי סעיפים שהעבודה עליהם
הסתיימה או לא. מה דעתך? שאצור משימה לכפתור כזה?

**Comment by akariv** [comment]
שים לב שהאינדיקציה הזו יכולה להשתנות שלא על ידי המשתמש - למשל אם התחלפה שנה
או שיש מכרז חדש שצריך לשייך.

**Comment by niryariv** [comment]
כן, זה בסדר גמור. נוכל גם להציג במסך הראשי את הסיבה לצורך בשנוי
