### ISSUE TITLE
דפי מפעיל של שירותי דת חסרים הסברים 

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#132]
כמו למשל חסר הסבר שהמספר משמאל למעלה הוא תשלום בשלוש שנים האחרונות.

**Comment by morchickit** [comment]
בכלל, למה הדף של שירות דת שונה ממפעילים אחרים?

**Comment by akariv** [comment]
לסוגי מפעילים שונים יש לנו דפים שונים בהתאם למידע שיש לנו עליהם.
כרגע קיימים ארבעה סוגי דפים:
- עמותות / חל״צ
- חברות בע״מ
- רשויות מקומיות
- ארגונים מסוג אחר

שירותי דת נופל תחת ההגדרה של ארגונים מסוג אחר, כאלו שיש לנו כמעט אפס אינפורמציה עליהם.
אפשר לנסות להרחיב את העמוד הזה כדי שיהיה קצת יותר דומה לדפים האחרים.

**Comment by akariv** [comment]
תוקן
