### ISSUE TITLE
שירות בעבודה 

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#135]
הוסף את האופציות הבאות - 
שירות בעבודה (לא הושלמו הנתונים)- לא לפרסום
שירות בעבודה (לא הושלמו הנתונים)- לפרסום

במקום הכפתור "שמירה והמשך עבודה".

**Comment by akariv** [comment]
כלומר שיהיו שני כפתורים נפרדים עם הטקסט הסופר ארוך הזה?

**Comment by morchickit** [comment]
כן, אפשר אולי לשנות - "שמור -  לא לפרסום" , "שמור - לפרסום"

**Comment by morchickit** [comment]
לבקשת יוני ושירה, אנחנו צריכים לשנות את הכפתור "שמירה - עדיין בעבודה, לפרסום" ל"שמירה - נתונים חסרים, לפרסום"
בנוסף, האם אפשר לשנות את צבע הכפתור "שמירה- סימון כהושלם" לירוק?

**Comment by morchickit** [comment]
הכפתור שמירה- סימון כהושלם לא ירוק. אפשר להפוך אותו לירוק? (נגיד #3fb543)

**Comment by akariv** [comment]
הכפתור ירוק...

<img width="402" alt="Screen Shot 2022-07-27 at 16 18 17" src="https://user-images.githubusercontent.com/265333/181256749-cc925e16-5795-4340-abc6-8960626c19ba.png">

**Comment by morchickit** [comment]
אה נהדר, לא ראיתי אותו כשנכנסתי למערכת קודם.

**Comment by morchickit** [comment]
אז אפשר לסגור!
