### ISSUE TITLE
דאשבורד הזנה - כמה שירותים הושלמו? 

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#136]
סיפור משתמש - "כצוות הפרוייקט אנחנו רוצים לדעת כמה שירותים הושלמו במלואם, כמה הושלמו חלקית אך פורסמו וכמה עדיין לא לפרסום."

לאחר הוספת #134 , יש לייצר טבלה המראה כמה שירותים הושלמו, כמה שירותים בעבודה - לפרסום, וכמה שירותים בעבודה לא לפרסום. 
הטבלה תראה מספר של כל השירותים, פר משרד ותחתיו פר מנהל. 
הגרף לא צריך להיות על ציר זמן אלא להראות תמונת מצב עדכנית (התאריך של היום)

**Comment by akariv** [comment]
איפה הטבלה הזו אמורה להופיע?

**Comment by morchickit** [comment]
אני חשבתי לעשות עמוד נפרד לכל זה, כך שזה לא בלוח הבקרה.

**Comment by morchickit** [comment]
אין טבלה, אבל התצוגה הנוכחית מראה את זה. סוגרת.
