### ISSUE TITLE
דף מפעיל -  חיבור מפעיל למכרז

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#139]
כאשר יש לנו מידע מדו"ח התקשרויות משרדי על מפעילים, יש לאפשר חיבור של מפעיל (שדה מספר מזהה בדוח התקשרויות, שהוא בעצם חפ) למספר מכרז המספר (שדה "מס' פנייה במנו"ף/מנור" בדו"ח עצמו). זאת בהנחה ו - 
1. אנחנו יכולים לקשר את המספר למכרז באתר המכרזים. 
2. אין פטור ממכרז 
כרגע מספר מנוף מכיל שני סוגי מספרים - האחד בעל 10 ספרות, זהו מספר חד ערכי ממערכת נעמ"ה. השני הוא מספר בן שש ספרות ממערכת מנו"ף הישנה. הוא לא חד ערכי. ההצעה היא כרגע לאפשר הזנה של שני המספרים, כאשר אנחנו נקטלג אותם לפי אורכם להאם הם מזהה מכרז ישן או חדש.

**Comment by akariv** [comment]
החיבורים האלה כבר קיימים - אפשר למצוא אותם למשל בדף המפעיל (בתחתית העמוד,
שאילתת מכרזים בהם זכה הספק).

**Comment by morchickit** [comment]
אבל אין באמת חיבור בין מכרז לשירות. מה שאני ראיתי בדף זה את כל המכרזים שמפעיל זכה בחלק אחד, כל השירותים בחלק אחר, אבל לא חיבור בין מכרז לשירות. צריך להוסיף שדה תחת - פירוט כל ההתקשרויות עם הארגון ב כל השנים שיהיה בו גם שם השירות.

**Comment by morchickit** [comment]
ראה פה - https://next.obudget.org/i/org/company/510913205?theme=soproc
יש את השורה הבאה 
![Screenshot 2022-06-06 at 15 02 01](https://user-images.githubusercontent.com/3273659/172176134-0b98172e-53eb-49eb-b4bc-965e3682ad02.png)

אבל לאיזה מהשירותים הרשומים פה היא רלוונטית? https://next.obudget.org/i/org/company/510913205?theme=soproc

**Comment by akariv** [comment]
במילים אחרות -
המשימה היא להוסיף לטבלת ההתקשרויות את השדה ״שם השירות החברתי״, אשר, אם
ישנו, ייגזר אוטומטית מדוחות ההתקשרות.
אני צודק?

**Comment by morchickit** [comment]
לא בדיוק, כי דוחות ההתקשרות, לא מראות שם שירות. בגדול אם הוכנס מכרז לשירות, ואנחנו רואים שהמכרז קיים בדוח התקשרות וב יש גם ספק, אז לקשר בין שניהם.

**Comment by akariv** [comment]
כן, אני כיוונתי לתוצר בפועל - הוספה של עמודה לטבלת ההתקשרויות בדף מפעיל ותו
לא.

**Comment by morchickit** [comment]
כן.

**Comment by akariv** [comment]
דוגמא: https://next.obudget.org/i/org/company/513684779?li=0&theme=budgetkey
