### ISSUE TITLE
מסך בית של משתמש

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#14]
כשמשתמש נכנס לשירות, מסך הבית שלו צריך להכיל:

1. שלום אבי!
2. לוגו של המשרד שהמשתמש משויך אליו (כשמודבר במשתמש רגיל עם הרשאות עריכה בלבד). לחיצה על הלוגו פותחת בחלון חדש את רשימת הסעיפים של המשרד בממשק ההזנה - למשל [משרד הבריאות](https://next.obudget.org/s/?q=&dd=activities&range=all&lang=he&publisher=health)
3. התראות ומשימות (בשלב זה: יש לך 127 סעיפים שטרם חוברו לתקנה תקציבית, 32 שחוברו ועדיין זקוקים לעריכה)
4. רשימה ניתנת לקיפול של סעיפים שדורשים חיבור לתקנה תקציבית
5. רשימה ניתנת לקיפול של סעיפים שחוברו לתקנה אבל דורשים הזנת שדות
6. רשימה ניתנת לקיפול של סעיפים שסומנו כמחוברים ומוזנים

הלוגו בפינה הימנית העליונה מקשר לדף הבית הנ״ל

**Comment by akariv** [comment]
באופן כללי אני חושב שכאן צריכות להופיע רק המשימות לביצוע, לא המשימות שכבר
בוצעו.
כך שמשתמש שמסיים את העבודה יקבל הודעה של ״כל השירותים מופו!״ סטייל ג׳ימייל
וסלאק

**Comment by akariv** [comment]
<img width="1354" alt="Screen Shot 2021-01-06 at 14 17 32" src="https://user-images.githubusercontent.com/265333/103776241-d57b8f00-5037-11eb-80be-3bea1d93e539.png">

**Comment by niryariv** [comment]
^צילום מסך לא עלה :)

**Comment by niryariv** [comment]
אפשר פשוט להציג את השירותים שמופו בתוך אלמנט שמקופל כברירת מחדל וככה לא להעמיס את המסך ומצד שני לאפשר למשתמש לראות אותם בלי לעבור לדף אחר

**Comment by akariv** [comment]
תזכור שהתצוגה הדיפולטית לשירותים היא לפי החלוקה הארגונית (משרד + שלוש רמות פנימה).
להציג את כל הרשימה ללא היררכיה זה פשוט לא ממשק משתמש טוב

עדיף בעיני להוסיף לעמוד השירותים החברתיים אפשרות סינון:
- הצג הכל
- הצג שירותים שדורשים מיפוי
- הצג שירותים שדורשים עדכון
(לא בטוח שיש משמעות להפרדה בין שתי הקטגוריות - אולי מספיק ״שירותים שדורשים התייחסות״)

ואז יוצגו רק האלמנטים הרלוונטיים, תוך שמירה על ההיררכיה הארגונית

**Comment by niryariv** [comment]
מבחינתי סבבה, רק אומר - בוא נשים את התוכן הזה בעמוד הבית של המשתמש במקום עמוד נפרד

**Comment by akariv** [comment]
מה אם אתה משתמש שלא אחראי על אף שירות? איך תראה את כלל השירותים הקיימים
במערכת?

**Comment by niryariv** [comment]
מה שמשתמש כזה יראה כשהוא נכנס לדף ״שרותים חברתיים״

**Comment by akariv** [comment]
אז בעצם כל המידע ישוכפל בשני הטאבים?

**Comment by niryariv** [comment]
הכוונה שלי לבטל את הטאב ״שרותים חברתיים״ ולאחד אותו עם דף הבית

בוא נדבר.. אני אתקשר מחר בבוקר

**Comment by niryariv** [comment]
זורמים עם אדם וסוגרים בינתים
