### ISSUE TITLE
ממשק הזנה - חיבור מכרז מפעיל 

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#140]
בממשק ההזנה, תחת לשונית "מכרזים ופטורים" , להוסיף עמודה עם מפעילים מקושרים למכרז, בה יהיה אפשר להזין ידנית מפעילים. הספקים יגיעו מלשונית מפעילים, אותם יזינו המובילים לפני לשונית מכרזים. 
על העמודה לאפשר הנה של יותר ממפעיל אחד למכרז.

**Comment by akariv** [comment]
<img width="751" alt="Screen Shot 2022-07-29 at 10 26 40" src="https://user-images.githubusercontent.com/265333/181707266-bb14b533-66f0-43d5-9886-9fe20bc360a7.png">
