### ISSUE TITLE
לשונית תקנה תקציבית - העברת פונקצית החיפוש

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#141]
פונקצית החיפוש לתקנה נמצאת כרגע מתחת לטבלה. פידבק ממשתמשות הוא להעביר את החיפוש ממתחת לטבלה למעל הטבלה, כדי שזה יקל על חיפוש תקנה לשירותים עם הרבה תקנות תקציביות
![Screenshot 2022-06-20 at 16 13 01](https://user-images.githubusercontent.com/3273659/174632828-8b3bb2d1-87b9-426a-9cd0-eeb9f4b195ef.png)

**Comment by akariv** [comment]
<img width="350" alt="Screen Shot 2022-06-27 at 17 15 58" src="https://user-images.githubusercontent.com/265333/175962763-95a37dfd-cd26-4a01-b87d-ca33384f62d6.png">

**Comment by morchickit** [comment]
מצוין!

**Comment by morchickit** [comment]
סוגרת את זה.
