### ISSUE TITLE
הרחבת סרגל אפשרויות - מחיקת שירות 

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#144]
הוספת כפתור בשם "מחיקת שירות". 
על הכפתור להיות בצבע אדום עם  אייקון של פח זבל. 
יש להוסיף הודעת אזהרה של "האם ברצונך למחוק את השירות?"

**Comment by akariv** [comment]
קיים כבר כפתור כזה - כאשר השירות לא פעיל אפשר למחוק אותו.

**Comment by morchickit** [comment]
זה לא באמת מוחק אותו אבל, זה רק מסמן אותו כלא פעיל, לא?

**Comment by akariv** [comment]
כאשר השירות פעיל הוא מסמן אותו כלא פעיל.
כאשר השירות כבר לא פעיל הוא מוחק סופית.

**Comment by morchickit** [comment]
לא הבנתי. איך הוא מבדיל בין פעיל ללא פעיל. חשבתי רק הסימון

**Comment by morchickit** [comment]
נראה אחלה. סוגרת
