### ISSUE TITLE
הצגת שירותים לא פעילים בלוח הבקרה

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#145]
בלוח הבקרה של השירותים, הוסף היררכיה של פעיל / לא פעיל שנמצאת תחת שם המכרז אבל מעל שם האגף. 
כך כל משרד יוכל לראות מה השירותים הפעילים לעומת הלא פעילים.

**Comment by akariv** [comment]
אולי עדיף להציג את זה כמסננים במקום כהיררכיה? (״הצג שירותים פעילים בלבד / הצג שירותים לא פעילים בלבד״)?

**Comment by morchickit** [comment]
ואז נעשה גם מסנן לפי - בעבודה / הושלם?

**Comment by akariv** [comment]
כן, אפשרי בהחלט

**Comment by morchickit** [comment]
מעולה. שאני אעשה אישיו חדש למסננים?

**Comment by morchickit** [comment]
Closing. Replaced by #147
