### ISSUE TITLE
כאשר תוקף של מכרז עומד להסתיים - הצג הודעה במכרז

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#146]
כאשר השנה בתוקף של מכרז שווה לשנה בתאריך של היום, הצג הודעה אזהרה תחת הלשונית במכרז "מכרז זה עומד לפוג השנה. אנא הזינו אופציה למכרז, קשרו מכרז נוסף או סמנו שירות כלא פעיל".

**Comment by akariv** [comment]
מה קורה כאשר יש יותר ממכרז אחד המחובר לשירות (המקרה הנפוץ)?

**Comment by morchickit** [comment]
והתוקף שלו לא עבר אתה מתכוון? לא יותר מדי, ההתראה היא פשוט כלי למשתמש לדעת שהם צריכים לעשות משהו עם המכרז הספיציפי הזה. אפשר להוסיף "אם המכרז לא בתוקף, השאירו מבלי לשנות"

**Comment by akariv** [comment]
לא הבנתי אבל מה הפעולה שהם צריכים לעשות עם המכרז.

דוגמא:
שירות עם 10 מכרזים משויכים, אחד פעיל והשאר היסטוריים. בכל התשעה יופיעו התראות?

**Comment by morchickit** [comment]
יופיעו התראות רק לשנה הנוכחית - משמע מכרז שפג תוקף ב-2022. לא לשאר המכרזים שפגו תוקף לפני זה.

**Comment by akariv** [comment]
מכרז שפג תוקפו ב-2022 (בין ינואר ל-28 ביוני נכון להיום) תופיע לידו התראה.
מכרז שעוד לא פג תוקפו (נגיד - מכרז פעיל שמסתיים ב-1 ביולי) לא תופיע לידו
התראה.

מדויק?

**Comment by morchickit** [comment]
בערך, אני מניחה שהזנה מתחילה מספטמבר, אז כל מכרז מינואר עד ספטמבר 22'.

**Comment by akariv** [comment]
דוגמא
https://data-input.obudget.org/he/datarecords/social_service/hp-lt-tvknyvt-lh-tsmh

<img width="1184" alt="Screen Shot 2022-07-27 at 16 26 31" src="https://user-images.githubusercontent.com/265333/181258494-5f7c990b-9748-4706-b2a5-c0880501d4ac.png">

**Comment by morchickit** [comment]
נהדר אתה!
