### ISSUE TITLE
מידע היסטורי - מכרזים - ממשק הזנה

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#149]
- [x] הוספת שדה פעיל / לא פעיל למכרז
- [x] אם תוקף פטור ממכרז הינו לפני התאריך הנוכחי, סמן תוקף פטור ממכרז כ"לא פעיל" אחר סמן "פעיל" 
- [x] אם תוקף מכרז עבר את התאריך של היום ואין לו אופציות, סמן אוטומטית "לא פעיל". אם תוקף מכרז + משך אופציות פג תוקף - סמן לא פעיל. אחר סמן פעיל. 
- [x] אפשר למשתמשים לשנות סטטוס מכרז

**Comment by akariv** [comment]
מה המטרה של סימון פעיל/לא פעיל עבור *פטור ממכרז* - הרי שם התוקף הוא קבוע ולא ניתן לשינוי או הארכה.
