### ISSUE TITLE
קישור בין מפתח התקציב לממשק ההזנה

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#15]
יש אפשרות לקשר בין דף פרטי שירות חברתי במפתח התקציב לדף העריכה שלו? באידיאל הקישור יופיע רק למשתמש שיש לו הרשאות עריכה. ראיתי שיש מנגנון לוגין במפתח התקציב..

**Comment by akariv** [comment]
כאמור, אני רוצה להימנע מלעשות שינויי ממשק ותשתית במפתח התקציב בשביל שניים
וחצי משתמשים.

**Comment by niryariv** [comment]
בוא נתחיל בקישור בין דף העריכה לדף בממשק הצפייה (ליד שם הסעיף, פותח חלון חדש)

**Comment by morchickit** [comment]
@akariv אני יכולה לסגור את זה?

**Comment by akariv** [comment]
כן
