### ISSUE TITLE
מידע היסטורי - מכרזים - ממשק צפייה 

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#150]
יש לחלק את לשונית הליכי רכש לשני חלקים - פעיל ולא פעיל. פעיל נמצא בראש הלשונית, לא פעיל בתחתית. 
יש לסדר את הרשימה בפעיל ולא פעיל בסדר כרונולוגי של פג תוקף כולל אופציות.

**Comment by morchickit** [comment]
@akariv יש מצב שסגרתי את זה בטעות..

**Comment by akariv** [comment]
אז תפתחי מחדש 🙂

**Comment by morchickit** [comment]
זה נעשה בעצם. סוגרת.
