### ISSUE TITLE
מקרא לסרגל מעקב בלוח בקרה

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#152]
כרגע לא ברור מה כל צבע מסמן, צריך להוסיף בלוח בקרה למעלה.

**Comment by akariv** [comment]
<img width="1189" alt="Screen Shot 2022-07-28 at 18 42 10" src="https://user-images.githubusercontent.com/265333/181580408-02bbd9f7-299c-4698-b7bd-177583413529.png">
