### ISSUE TITLE
תקנות תקציביות - הצג רק משנת 2017

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#155]
כרגע המערכת מאפשרת הצגה של תקנות תקציביות של עד שנת 1997. במקרה שמספר של תקנה תקציבית דומה לאורך מספר שנים, אפשר הצגה של עד שנת 2017.

**Comment by akariv** [comment]
מדובר במערכת ההזנה או במערכת התצוגה?
מה המוטיבציה? למה לא לאפשר למי שמעוניין להזין מידע היסטורי?

**Comment by morchickit** [comment]
מערכת ההזנה. זה פשוט מבלבל את המשתמשת. אנחנו גם ככה ביקשנו מהם להזין מידע שנה שעברה מ- 2017, אז הם לא הולכים להזין מידע מלפני זה גם ככה. מידע מהעבר יותר לא מזיק, אבל הוא גם לא מועיל כרגע אז חבל לבלבל אותם
