### ISSUE TITLE
מפת מפעילים לא עובדת 

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#158]
היא לא מראה איפה וכמה מפעילים 
<img width="294" alt="Screenshot 2022-08-30 at 16 57 10" src="https://user-images.githubusercontent.com/3273659/187484508-8757ed75-94a1-4905-8787-952d750d6ca5.png">
נגיד פה -  https://www.socialpro.org.il/i/activities/gov_social_service/sh-t-khyrvm-mrkzy-khvsn?theme=soproc

**Comment by akariv** [comment]
![Screenshot_2022-08-30-19-13-12-558_org.mozilla.fenix.jpg](https://user-images.githubusercontent.com/265333/187487717-137d3a63-2a61-4279-ad2a-bb49b8ab65ab.jpg)

אצלי זה נראה בסדר...

**Comment by morchickit** [comment]
מוזר. אולי כי הסתכלתי מספרי? אבדוק.

**Comment by morchickit** [comment]
זו אכן בעיה בספארי... עובד טוב בכרום
