### ISSUE TITLE
מידע היסטורי ממשק צפיה  - דף הבית 

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#159]
מידע היסטורי בממשק ההזנה מפעיל ומכרז יכולים להיות פעיל / לא פעיל . 
בממשק הצפייה אנחנו צריכים לשנות את השם למפעיל עבר (לא פעיל) מול מפעיל עדכני (מפעיל פעיל). 

בלשונית מפעילים בדף הבית - הוסף עמודה של סטטוס - מפעיל עבר מול מפעיל עדכני. אפשר Sort by הצגה של כל המפעילים הפעילים לפני המפעילים הלא פעילים. הוסף שדות אלו לאקסל. 

בלשונית הליכי רכש בדף הבית  - הוסף עמודה סטטוס מפעיל עבר מול מפעיל עדכני הוסף שדות אלו לאקסל 
 יש להבדיל בין סטטוס פעיל ללא פעיל על ידי מתן צבע טקסט שונה אפור ו-italic מול פעיל (צבע טקסט שחור)

**Comment by akariv** [comment]
- האם יש גם שינויים בעמוד השירות (לפי הכתוב אני מבין שרק בדפים הסיכומיים)?
- מה לגבי מקרה בו מפעיל הוא פעיל בשירות אחד ולא פעיל בשירות אחר? כיצד יופיע בטבלה?
- הליכי רכש - האם התכוות לכתוב הליך עבר מול הליך פעיל?
- שינוי סגנון הטקסט - לתוכן של כל העמודות? רק עמודה ספציפית?

**Comment by morchickit** [comment]
עמוד שירות נמצא באישיו נפרד פה - #160 
- אם יש מפעיל שהוא פעיל בשירות אחד אבל לא באחר הוא יחשב בדיפולט לפעיל. 
- הליכי רכש - אכן הליך עבר מול פעיל 
- שינוי סגנון טקסט לכל העמודות למעט איפה שהתוכן הוא קישור

**Comment by akariv** [comment]
@morchickit 
משהו חשוב לדייק כאן - 
האם מדובר גם על מפעילי עבר בשירותים שכבר לא פעילים? או רק מפעילים שהפסיקו להיות פעילים בשירותים הפעילים כיום?
כרגע האתר מציג רק שירותים פעילים (למשל, בטבלת השירותים אין מקום שמציג שירותים לא פעילים ולא ראיתי גם בקשה להציג אותם).

**Comment by morchickit** [comment]
לפי סיכום הפיגשה היום - 
"מעניין אותנו שמפעיל לא בפעיל בתוך שירות אחד. מפעיל לא פעיל אם הוא לא פעיל בכל שירותים. שירות לא פעיל אם הוא היה פעיל ב-2020 ולא פעיל מ-2021"


מפעיל בהליך רכש לא פעיל הוא לא פעיל אלא אם כן יש לו עוד מכרז

**Comment by akariv** [comment]
השאלה היתה לגבי מה מציגים ברשימה - אם יש מפעיל שמופיע רק בשירותי עבר (שכבר לא פעילים), האם הוא יוצג?
לכאורה הוא לא אמור להיות מוצג, כי בשום מקום באתר אנחנו לא מציגים את רשימת השירותים הלא פעילים. 
כנ״ל לגבי מכרזים - האם להציג מכרזים של שירותים היסטוריים שכבר לא פעילים?

ספציפית לגבי מה שכתבת, יש מקום אחד בו מגדירים אם מפעיל הוא פעיל או לא פעיל - בלשונית המפעילים.
רק כאשר יהיה מיפוי מלא בין מכרזים למפעילים נוכל להשתמש במידע של מכרז פעיל/לא פעיל ולהשליך ממנו על המפעיל.
