### ISSUE TITLE
להכניס היררכיה תוך משרדית מתוך ספר 2018

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#16]
### משרד הבריאות
- חטיבת רפואה
  - האגף לגריאטריה
  - האגף לבריאות הנפש: המחלקה לשיקום
  - האגף לבריאות הנפש: המחלקה לאוטיזם וטראומה נפשית
  - האגף לבריאות הנפש: המחלקה לטיפול בהתמכרויות
  - רפואה כללית: טיפול באוכלוסיות מיוחדות
  - אגף השיקום: המחלקה לרצף שיקום, פרוטזות ואורטזות
  - אגף לבריאות השן
  - עבודה סוציאלית
- בריאות הציבור
  - תזונה
  - שחפת ואיידס
  - מחלקה לאם לילד ולמתבגר
  - קידום בריאות
  - גנטיקה קהילתית
 
### משרד הרווחה
- מינהל מוגבלויות
  - שירות דיור תומך
  - השירות לטיפול באדם עם אוטיזם
  - השירות לשיקום מקצועי תעסוקתי
  - השירות לעיוור
  - שירות לקהילה
  - השירות לשיקום וטיפול בקהילה
- מינהל שירותים אישיים וחברתיים
  - ילד ונוער
  - השירות לרווחת הפרט והמשפחה
  - ״נושמים לרווחה״ במרכזי עוצמה
  - התנדבות
  - עבודה קהילתית
  - שירות למען הילד
- מינהל הסיוע לבתי המשפט ותקון
  - רשות חסות הנוער
  - השירות לטיפול בהתמכרויות
  - השירות לנוער, צעירות וצעירים
  - שירות המבחן למבוגרים
  - השירות לשיקום נוער
  - שירות המבחן לנוער
  - השירות לחקירות ילדים, חקירות מיוחדות
- אגף בכיר לאזרחים ותיקים
  - שירות לאזרח הותיק

### משרד החינוך
- מינהל פדגוגי
  - תוכניות משלימות למידה
  - האגף לחינוך יסודי
  - האגף לחינוך תלמידים ונוער בסיכון
  - האגף לתקציב ומינהל
  - האגף לחינוך מיוחד
  - האגף לתלמידים מחוננים ומצטיינים
  - האגף לשירות פסיכולוגי ייעוצי (שפ״ע)
  - האגף לחינוך על-יסודי
  - האגף ליישומי חוק ומדיניות
  - אגף זה״ב, נגישות ואורח חיים בטוח
  - האגף לקליטת תלמידים עולים
- מינהל חברה ונוער
  - אגף חברתי קהילתי
- מינהל מדע וטכנולוגיה
  - מינהל מדע וטכנולוגיה
- מזכירות פדגוגית
  - אגף מורשת
  - אגף מדעים
  - אגף רוח וחברה
  - אגף מורשת עם אגף אומנויות
- מינהל הכשרה והתפתחות מקצועית לעובדי הוראה
  - פיתוח מקצועי לעובדי הוראה
  - התמחות וכניסה להוראה
- מינהל החינוך הדתי
  - מינהל החינוך הדתי
- מינהל תיאום ובקרה
  - אגף לחינוך מבוגרים
- אגף נכסים ולוגיסטיקה
  - אגף נכסים ולוגיסטיקה

### משרד העלייה והקליטה
(ההיררכיה כאן היא ברדק עוד יותר גדול מהאחרים, כנראה נצטרך לסדר את זה מתישהו אם/כאשר נעבוד מולם)
- אגף בכיר דיור
  - (ריק)
- חטיבת פרט
  - אגף תעסוקה
  - יזמות
  - מינהל הסטודנטים
  - צעירים
  - קליטה במדע
  - קליטה במדע ואגף היזמות
  - צה״ל
  - קליטה בקהילה
- חטיבת רשויות, ארגונים וקהילה
  - שירות הרווחה
  - קליטת עולי אתיופיה
- חטיבת עידוד עליה
  - (ריק)

**Comment by niryariv** [comment]
הכוונה היתה שבמסך ״שירותים חברתיים״ השירותים יוצגו לפי ההיררכיה הנ״ל - כלומר תחת משרד הרווחה יהיו ארבעת המינהלים שלו, תחת כל אחד מהם אגפי השירות השונים של המנהל ותחתיהם הסעיפים עצמם

**Comment by akariv** [comment]
זה כבר ככה...

**Comment by niryariv** [comment]
כרגע יש שתי דרגות היררכיה (משרד - מינהל) צ״ל שלוש (משרד - מינהל - אגף)

![Screen Shot 2021-01-19 at 13 08 47](https://user-images.githubusercontent.com/1771/105026675-7bc38d80-5a57-11eb-87fb-8e9382d9e3b0.png)

**Comment by akariv** [comment]
ככה זה מופיע בספרים

**Comment by niryariv** [comment]
בספר יש חלוקה לפי משרדים ואז היררכיה של מינהל/אגף (את הרשימה למעלה הוצאתי מהספר של 2018:
 
![Screen Shot 2021-01-19 at 13 16 20](https://user-images.githubusercontent.com/1771/105027597-9fd39e80-5a58-11eb-941a-787804422ca4.png)

**Comment by akariv** [comment]
וככה זה מופיע ב-ui:

<img width="545" alt="Screen Shot 2021-01-19 at 13 26 36" src="https://user-images.githubusercontent.com/265333/105028671-ff7e7980-5a59-11eb-8aa5-e0968f2a9be4.png">

עם אותה ההיררכיה

**Comment by niryariv** [comment]
ב 2018 יש 4 מינהלים במשרד הרווחה, באתר יש 16 אפשרויות מתחת ״משרד הרווחה״. נראה לי שהבעיה נוצרת בגלל שמות שונים למינהלים בספרים משנים שונות.. מתייג כשאלה לפגישה איתם

**Comment by akariv** [comment]
זה בדיוק מה שהעליתי מולם בפגישה הקודמת - שההיררכיה לא ברורה וכל שנה שינו את
השמות.

**Comment by niryariv** [comment]
אם אני זוכר נכון התשובה היתה שהולכים לפי החלוקה של 2018. כמובן אז צריך למפות את הקודמות לשמות הנוכחיים, והשאלה אם הן אכן מתמפות. נשאיר את זה כשאלה לדיון

**Comment by akariv** [comment]
ברור, הולכים לפי החלוקה של 2018 אבל את המידע של 2017 ו-2016 צריך לתקן ידנית.

אפשר לעשות זאת במערכת ועל הדרך לאחד רשומות של שירותים זהים שמופיעים תחת
שמות שונים בשנים שונות.
