### ISSUE TITLE
מידע היסטורי דף שירות - ממשק צפייה 

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#160]
- בלשונית מפעילים בדף שירות - הוסף עמודה של סטטוס - פעיל/לא פעיל. Sort by הצגה של כל המפעילים הפעילים לפני המפעילים הלא פעילים. הוסף שדות אלו לאקסל 
- בלשונית הליכי רכש בדף שירות - הוסף עמודה סטטוס (פעיל לא פעיל), הוסף שדות אלו לאקסל 
- הורד את העמודה יחידה ארגונית בטבלת הליכי רכש

יש לשמור על אותה שפה ועיצוב כמו ב- #159

**Comment by akariv** [comment]
> הורד את העמודה יחידה ארגונית בטבלת הליכי רכש

אין בעיה, רק מציין שבלי הקישור הזה אין אפשרות בכלל להגיע מעמוד השירות לעמוד היחידה הארגונית הרלוונטית עבורו (למשל משירות של משרד הרווחה לעמוד של משרד הרווחה)

**Comment by morchickit** [comment]
צריך לשאול את שירה על זה...
