### ISSUE TITLE
קישור מפעיל - הליך רכש - דף הבית 

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#162]
בלשונית הליכי רכש בדף שירות ובדף הבית  -הוסף עמודה "מפעילים מקושרים". אם יש יותר משלושה מפעילים, תן אפשרות להציג חלונית להרחבה

**Comment by akariv** [comment]
הוספתי את רשימת 3 המפעילים הראשונים.

ההרחבה צריכה להתבצע על ידי יצירת קישור לעמוד המכרז במפתח התקציב - עד כה לא עשינו את זה, אבל אולי כדאי לשנות את זה עכשיו.
