### ISSUE TITLE
בדף הבית - אפשר לסנן על סטטוס מפעיל ("פעיל / לא פעיל)

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#163]
אפשר סינון בדף הבית על סטטוס מפעיל - פעיל / לא פעיל

**Comment by akariv** [comment]
לא הבנתי מה הסינון אמור לעשות?

**Comment by morchickit** [comment]
לאפשר לסנן בגרפים לפי פעילות מפעיל. אני יודעת שהיום זה מציג רק פעילים, אבל לתת הזדמנות ליוזר להסתכל גם על לא פעילים. אני כן מבינה עכשיו שתהייה בעיה עם מפעיל הוא פעיל במקום אחד ולא פעיל באחר...

**Comment by akariv** [comment]
כן, נראה לי שיש לזה פוטנציאל לבלבל מאוד.
בכל מקרה, את השירותים עצמם זה לא יכול לסנן אז...

**Comment by akariv** [comment]
אולי נסתפק פה בשינויים של #159 ?
