### ISSUE TITLE
עמוד בית - לשונית תהליכי רכש

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#166]
יש להוסיף לשונית חדשה בשם "תהליכי רכש". 
שאלות מנחות ללשונית - 
- כמה מכרזים וכמה פטורים יש בכל משרד?
- מה מספר הפטורים שיש בכל משרד? מאיזה סוג? 
- באיזה מודל תמחור משתמשים הכי הרבה בכל משרד? 
- בכמה שירותים יש פטור מסוג ספק יחיד, מיזם משותף והתקשרות עם רשות מקומית

גרפים שצריך ליצור - 
- מספר הליכי רכש לפי סוג הליך (מכרז/פטור ממכרז) ולפי משרד
- מספר פטורים לפי סוג פטור ולפי משרד
- מספר הליכי רכש לפי מודל התמחור (תקף רק להליכי רכש שהם מכרז, לא לפטורים שם אין מודל תמחור)  ולפי משרד
- מספר שירותים עם פטור מהליך מכרזי – ספק יחיד, מיזם משותף, התקשרות עם רשות מקומית - ולפי משרד

מסמך איפיון של שירה ויוני נמצא פה: https://docs.google.com/document/d/12SNV5w773mA0OGKHTh_3gIeSJHoGUYTu/edit

**Comment by akariv** [comment]
אין לי גישה למסמך
