### ISSUE TITLE
גרפים בעמוד הבית - הצגת פילטור

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#168]
הגרפים כרגע מציגים מספרים. כאשר בוחרים סינון על פילטר מסויים, יש להוסיף בתיאור הגרף כמה שירותים נבחרו ולהוסיף מתוך כמה שירותים בכללי הם. 
למשל - כאשר מפלטרים על מודל תמחור הצעת מחיר - כרגע מופיע כי סה"כ יש 190 מפעילים במודל תמחור הצעת מחיר. יש לכתוב "סה"כ 190 מפעילים מתוך 948 מפעילים (המספר הכללי של המפעילים). 
יש להוסיף כמה זה באחוזים מסך הכל (במקרה של הצעת מחיר - 20%). 

אדם, זה אפשרי בכלל עם פלוטלי?

**Comment by morchickit** [comment]
התיאור המקורי מאבני הדרך - "- הצגת אחוז ולא רק מספר – למשל בוחרים הצעת מחיר, כמה זה באחוזים מכלל המודלים של התמחור"

**Comment by akariv** [comment]
אני הבנתי את זה כך שבגרפים של העמודות נציג את העמודות כאחוזים ולא רק
כמספרים - לא את האחוז על הפילטור.

**Comment by morchickit** [comment]
נברר זאת בחמישי!

**Comment by akariv** [comment]
מה בסוף הוחלט פה?

**Comment by morchickit** [comment]
לא רלוונטי. סוגרת
