### ISSUE TITLE
להבליט אלמנט סיום מיפוי

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#17]
כיום נראה כך, באמצע הטופס:

![Screen Shot 2021-01-11 at 12 21 11](https://user-images.githubusercontent.com/1771/104168961-805cc600-5407-11eb-993c-c5cdade2c247.png)

להוריד למטה, לשורת הכפתורים:
![Screen Shot 2021-01-11 at 12 21 32](https://user-images.githubusercontent.com/1771/104168994-8ce11e80-5407-11eb-86bf-276d4fa606f5.png)

לתת רקע כתום וטקסט ״בעריכה״. כשהסמן מעליו הרקע הופך ירוק והטקסט ״עריכה הושלמה״. לחיצה מקבעת את המצב ואז במעבר סמן הרקע כתום וכו׳

**Comment by niryariv** [comment]
סבבה אבל תן להם איזה צבעים, הממשק מבאס. אולי כתום - ירוק  - אדום?
![Screen Shot 2021-01-19 at 13 11 51](https://user-images.githubusercontent.com/1771/105027010-e96fb980-5a57-11eb-9b09-f4bf1ea5783d.png)

**Comment by akariv** [comment]
שנעשה מעבר שלם על העיצוב עם איזה מעצב, נעבור על הצבעים, הפונטים והריווחים
(כלומר, לא רק פה)?

**Comment by niryariv** [comment]
אני חושב שנעשה את זה כשנקח מעצב לממשק הצפיה, נבקש שיקדיש שעה לממשק הזה. אבל פה מדובר על משהו זעיר, לדעתי שווה להוסיף רק לצורך ההדגמות. לשיקולך

**Comment by niryariv** [comment]
@akariv יכול להיות שבמקום להוריד את הכפתור הזה למטה העלית את האחרים למעלה? :) הם נראים קצת מוזר באמצע הטופס..

**Comment by akariv** [comment]
כן, אחרת לא רואים אותם (צריך לגלול ממש למטה).
יכול להיות שגם פתיר בעיצוב.

**Comment by niryariv** [comment]
אולי לשים את הכפתורים באלמנט של 
sticky footer
(או אלמנט צף אחר כלשהו)?
