### ISSUE TITLE
ספק שזכה בפטור לא מופיע בטבלת הליכי רכש כספק של ההליך. 

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#176]
על אף שאנחנו מקשרים אוטומטית ספקים שזכו בפטור, הם לא מופיעים בעמוד הבית או בעמוד השירות כספקים שזכו בפטור. 
דוגמא של דף השירות של אשפוזיות גמילה - 
<img width="1259" alt="Screenshot 2022-11-23 at 16 13 06" src="https://user-
images.githubusercontent.com/3273659/203596472-d09a2b3b-a95d-465d-9b3d-9ad4fd13d20f.png">
ושל המידע בעמוד 
https://data-input.obudget.org/he/datarecords/social_service/shpvzyvt-gmylh-msmym-lkvhvl-vkhvmrym-psykvqtybyym

**Comment by akariv** [comment]
הבאג היה שכאשר מוסיפים ידנית פטור לרשימת הליכי הרכש, המפעיל שלו לא התווסף לרשימת המפעילים במערכת ההזנה (ממנה נגזרת רשימת המפעילים באתר הצפיה).

תוקן באופן הבא - 
מעכשיו, כאשר מקשרים פטור לשירות, המפעילים שלו יתווספו אוטומטית לרשימה.
כל שירות שכבר מחוברים לו פטורים עם מפעילים שאינם ברשימה יתוקן אוטומטית ברגע שיפתח שוב במערכת ההזנה.

לא ניתן לבצע את התיקון הזה אוטומטית, שכן יש פרמטרים שצריך להזין עבור כל מפעיל שמקשרים לפני שאפשר לשמור.

בכל מקרה, ייצרתי רשימה של השירותים עם הבעיה הזו, אפשר לראות אותה כאן: https://redash.hasadna.org.il/queries/1220#1420
