### ISSUE TITLE
הצג בעתיד בגרפים רק ספקים פעילים או הליכי רכש פעילים 

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#177]
כדי שיהיה לנו מידע על מצב הווה כרגע

**Comment by akariv** [comment]
מה הכוונה ב״הצג בעתיד״?

**Comment by akariv** [comment]
@morchickit

**Comment by morchickit** [comment]
נראה לי פשוט ניסחתי את יוני. הכוונה היא עכשיו להראות רק פעילים  בגרפים
