### ISSUE TITLE
כאשר נגמר תוקף של פטור ממכרז יש לסמן אותו כלא פעיל באתר הצפייה.

### ISSUE THREAD

**Issue by morchickit** [hasadna/social-procurement#184]
ראה דוגמה פה - https://www.socialpro.org.il/i/activities/gov_social_service/yy-vts-vnyhvl-spqt-shyrvtym-bvr-nky-gpyym?theme=soproc

הפטור ממכרז פכ תוקף ב- 2018, אך הוא מסומן כפעיל באתר. הוא אמור להיות מסומן כלא פעיל.

**Comment by morchickit** [comment]
אני עדיין לא רואה שינויים לזה באתר

**Comment by akariv** [comment]
יקח לזה עוד כמה דקות להתעדכן באתר.
אני אסגור את האישיו כשזה יהיה באוויר.
