### ISSUE TITLE
פער תצוגת תקציב מאושר משרד החינוך לשנת 2021

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#188]
הסתכלתי בדשבורד, לא ראיתי סיבה לפער בהבדלים:
בגרף תקציב מאושר התקציב ל2021 הוא 1,746,920,032 ש"ח
בגרף "תקציב לאורך זמן" תקציב מאושר הוא 1,075,233,481

**Comment by akariv** [comment]
הבעיה היא בשירות הזה:

https://data-input.obudget.org/he/datarecords/social_service/mtn-shyrvtym-mynhlyym-lhp-lt-tvknyvt-hznh-shl-mshrd-hkhynvk
השירות מסומן כפעיל אבל תקציב 2021 הוא 0.

כרגע השאילתא של ״תקציב מאושר״ מציגה את התקציב האחרון שהוזן לכל השירותים
הפעילים. שיניתי אותה כך שתציג את תקציבי 2021 בלבד (יתעדכן בשעות הקרובות).
