### ISSUE TITLE
האם יש תהליכי הזנת נתונים אוטומטיים/חצי אוטומטיים ברווחה?

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#189]
האם יש אפשרות לטעון קובץ אקסל להזנת הנתונים?
יוני הזכיר במייל וגם מבין מהקשר ההנחיות של מור. האם זה בוצע בעבר ואפשרי כעת?

 תודה

**Comment by akariv** [comment]
לא, אין אפשרות כזו. 
אם רוצים אפשר לפתח מערכת הזנה מבוססת אקסל, אבל רמת המורכבות שלה תהיה באותו סדר גודל של מערכת ההזנה הנוכחית.

**Comment by emrib** [comment]
כלומר, כל ההזנה וההתאמה הן כרגע רק ע"י משתמש קצה דרך ממשק הזנה קיים?

**Comment by akariv** [comment]
כן
