### ISSUE TITLE
מס' מפעילים

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#197]
באג תוקן ב06/08/2023
יוני טוען שהיו לפני תיקון הבאג 877, כעת יש 794.
השאלה היא כמה מפעילים יש באמת? 
האם תיקון הבאג תיקן הזנות אוטמטיות שגויות שקרו במהלך 2022 ולא רק במהלך 2023?

דבר שני,
במספר מפעילים לאורך זמן - האם המפעילים נספרים פעמים בין המשרדים ולכן מספרם עולה על הסך הכל?

אודה להסבר לתקלה ומה המספר 794 מייצג כיום. 

תודה

**Comment by akariv** [comment]
הבאג היה שספרנו מפעילים מ״העתיד״ (כאלו שרק התחילו ב-2022) כמפעילים פעילים, עכשיו אנחנו כבר לא עושים את זה.
- מפעילים פעילים נחשבים רק בתקופת הפעילות של השירות (כלומר, לא אחרי 2022)
- מספר מפעילים לאורך זמן - הגרף הוא פר משרד, אז אם מפעיל בשני משרדים הוא יופיע בכל אחד מהם בנפרד
