### ISSUE TITLE
תצוגת מפעילים באתר מפתח לרכש חברתי

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#199]
"עבור חלק מהמכרזים מוצג באתר 0 מפעילים, נכנסתי לממשק ההזנה וראיתי שכן משוייך מפעיל ל-2021. למשל עבור "שירותי טיפת חלב בכפר עקב"

זה לא עבור כל המכרזים , כמה עשרות טובות
כשהורדתי טבלת אקסל הוצגו אותם נתונים

האם זה כי ערכו את "תחילת פעילותו" של  המפעיל במכרז ל2023?
אם כן, זה קשור לברירת מחדל של עדכון השדה של התאריך?

![Image](https://github.com/hasadna/social-procurement/assets/76155903/2e7019b5-c76d-4e43-a351-687962f8e08c)

**Comment by akariv** [comment]
אם המפעיל התחיל את פעילותו ב-2023, הוא לא אמור להיות מוצג באתר הצפיה (כי אנחנו מציגים מידע עד 2021 ולא אחרי זה), כך שמבחינתנו המפעיל הזה לא קיים.
