### ISSUE TITLE
שכאשר מחזירים שירות מסטטוס "לא פעיל" ל"פעיל" נמחקות כל ההגדרות.

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#200]

**Comment by akariv** [comment]
עכשיו ניסיתי לשחק עם השירות ״אושרת ותות ניסיון״ (שמסומן כלא פעיל).
העברתי אותו להיות פעיל ולא פעיל מספר פעמים, המפעילים בתוכו נשארו מוגדרים
ולא נמחקו.

אבל, כן מצאתי באג שגורם לשינוי שנת תחילת הפעילות של מפעילים (לא קשור לשינוי
פעיל/לא פעיל).

**Comment by emrib** [comment]
תודה, תוכל להגיד שהבאג יתוקן? האם התיקון יחזיר את הנתון לקדמותו?

‫בתאריך יום ד׳, 6 בספט׳ 2023 ב-13:38 מאת ‪Adam Kariv‬‏ <‪
***@***.***‬‏>:‬

> עכשיו ניסיתי לשחק עם השירות ״אושרת ותות ניסיון״ (שמסומן כלא פעיל).
> העברתי אותו להיות פעיל ולא פעיל מספר פעמים, המפעילים בתוכו נשארו מוגדרים
> ולא נמחקו.
>
> אבל, כן מצאתי באג שגורם לשינוי שנת תחילת הפעילות של מפעילים (לא קשור
> לשינוי
> פעיל/לא פעיל).
>

**Comment by akariv** [comment]
הבאג תוקן, אבל הוא לא ידע להשיב את הערכים לקדמותם. אפשר לשנות את כל
המפעילים ידנית כך שיוחזרו לשנת תחילת הפעילות של השירות.
