### ISSUE TITLE
שינויים בהצגת הנתונים במפתח רכש חברתי

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#205]
יוני תיאר היום בפגישה מצב בו הפרמטרים של מס' שירותים ומס' מפעילים מציגים נתונים שונים ומשתנים לאורך זמן. האם מכיר והאם יודע מה יכולה להיות הסיבה? יש דרך לבדוק? האם קשור להזנה של הרפרנטים? 

תודה

**Comment by akariv** [comment]
תצטרך להיות טיפה יותר קונקרטי בשביל שאוכל להתייחס...

**Comment by emrib** [comment]
זה הכי טוב שהיה לי מיוני בפגישה. אנסה שוב לדלות איך שהוא. שני הפרמטרים האלו זה מה שהצלחתי להבין וגם שזה היה בחודש האחרון. אחזור אלייך אם מה שאוכל. תודה
