### ISSUE TITLE
שינויים בנתוני מינהל שירותים אישיים וחברתיים

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#206]
**שירותים למחיקה:** 
a.       אומנה - אומנת חירום (חלק משירות האומנה "הרגילה" – גם מהותית וגם במכרזים המצויינים באומנה)
b.      רווחת הילד והמשפחה - השביל המיטיב – נכלל בשירות שניתן בתוכנית נושמים, אין סיבה שיופרד משם.
g.       חוק - יחידה טיפולית ייעוצית (זה חלק ממרזי חירום וניתן מאותו המכרז
i.         תחום לוועדות ערר – למחוק, לא רלוונטי לרכש חברתי

**שינויי היררכיה:**

- תחת אחר כרגע יש את תוכנייו האוריינות הדיגיטלית - רק אותה צריך להשאיר תחת אחר. שאר התוכניות תחת אחר צריכות להיות תחת אגף תעסוקה שכן צריך לפתוח.

- חוץ ביתי = "אגף בכיר חוץ ביתי והשמות מיוחדות"

b.      אין "קהילה" אלא - אגף בכיר משפחות ילדים ונוער בקהילה שמכיל את השירותים: שירות הגנה וטיפול  במצבי טראומה ומשבר, השירות לרווחת המשפחה והילד, תוכניות טיפול במשפחה ובילד (שירות שכרגע אין רכש חברתי תחתיו, אפשר אולי להכניס ושיהיה ריק למען הסדר)

c.       חוק: צריך להיות "חוק הנוער" וזה צריך להיות תחת אגף בכיר משפחות ילדים ונוער בקהילה

d.      אין "קהילה" אלא "אגף בכיר משאבי קהילה" שמכיל את השירות להתנדבות (שאמור להיות ריק כרגע), השירות לעבודה קהילתית

**Comment by akariv** [comment]
- [x] אומנת חירום: סומן כלא פעיל
- [x] השביל המיטיב: סומן כלא פעיל
- [x] יחידה טיפולית ייעוצית: סומן כלא פעיל
- [x] תחום לוועדות ערר - אין שירות כזה... @emrib 
- [x] נוסף אגף ״תעסוקה״ תחת ״שירותים אישיים וחברתיים״
- [x] השם של אגף ״קהילה״ שונה ל״משפחות ילדים ונוער בקהילה״
  - [ ] תחת ״משפחות ילדים ונוהר בקהילה, האם למחוק את היחידות: ״ טיפול במשפחה – תהליכים, ועדות ותכניות״, ״תחום לוועדות ערר וסיוע ליחידים ומשפחות״, ״השירות לעבודה קהילתית״, ״תחום התנדבות״ @emrib 
- [x] השם של אגף ״חוץ ביתי״ שונה ל״חוץ ביתי והשמות מיוחדות״
- [x] הוספתי יחידת ״חוק הנוער״ תחת ״משפחות ילדים ונוער בקהילה״ (זה לא סותר את מה שנאמר קודם? @emrib)
- [ ] לשנות את השם של אגף ״קהילה״ ל-״משאבי קהילה״ - צריך לבחור שם אחד שאליו משנים @emrib 

סימנתי את מה שכבר בוצע, השאר פתוח להערות שלך.

אחרי השינויים, שיעברו על השירותים השונים וישימו אותם במקום הנכון בעצמם.

**Comment by emrib** [comment]
<img width="543" alt="image" src="https://github.com/hasadna/social-procurement/assets/76155903/9f1afb22-79b9-431f-bca0-b70591655de6">

נראה שחלק מהשינויים בהיררכיה בוצעו אך לא נראים בלוח בקרה

**Comment by akariv** [comment]
לא הבנתי מה אתה מראה לי בתמונה.

כפי שכתבתי, שינויים בשמות ההיררכיה לא משתקפים בשירותים אוטומטית. צריך לעבור על השירותים השונים ולהעביר אותם למקום הנכון ידנית.

**Comment by emrib** [comment]
ישבתי עם אופיר, מרכז כאן ההתייחסות שלי לשינויים. היא כוללת דרישות נוספות וסופיות שהיא העלתה:

**מחיקה**
 אומנת חירום: סומן כלא פעיל -> **למחוק**
 השביל המיטיב: סומן כלא פעיל -> **למחוק**
 יחידה טיפולית ייעוצית: סומן כלא פעיל -> **למחוק**
 תחום לוועדות ערר - אין שירות כזה.. -> הכוונה למחוק את הענף בהיררכיה שנקרא "תחום לוועדות ערר וסיוע ליחידים ומשפחות"
 
**שינוי היררכיה**
בהמשך להתייחסות הקודמת עם הצילום מסך, נראה ששינויי ההיררכיה לא שוקפו בלוח בקרה אל בהגדרות השירות. מבין מההערה שלך שאם יש הירככה חדשה ולא שוייך לה השירות אז לא יראה שם ההירכיה החדשה?

אשלח את ההיררכיה  המעודכנת כוללת את השינויים החדשים במייל כי כאן זה מתחרבש בעברית

**Comment by akariv** [comment]
אם השירות היה פעיל בעבר אז אנחנו לא מוחקים אלא מסמנים כלא פעיל.

אם הוא לא היה פעיל בעבר, צריך לוודא שכל התקציבים שכרגע משוייכים אליו מאז 2020 יועברו לשירות הנכון.

בצילום המסך רואים את אגף תעסוקה תחת שירותים אישיים וחברתיים - זה לא האגף שביקשתם להוסיף?

**Comment by emrib** [comment]
כן, אבל לא רואים את אגף תעסוקה כאן:
<img width="465" alt="image" src="https://github.com/hasadna/social-procurement/assets/76155903/16d1554a-ddff-4ec2-b890-1eeb3480dbc4">

**Comment by akariv** [comment]
ברגע שתעבירו לאגף הזה שירותים הוא יופיע בלוח הבקרה. אגפים בלי שירותים לא
מופיעים בלוח הבקרה.
