### ISSUE TITLE
שינוי סטטוס שירות לא ישפיע על נתונים היסטוריים

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#208]
זו הדרישה של יוני בהמשך לשיחה שלנו היום לגבי פערים בתצוגות של נתונים שנתיים ורב שנתיים. 
 יוני ביקש שהשינוי בגרפי המגמה, זה לא יהיה דינמי, אלא שזה תהיה תמונת מצב. ששינויים שמתצעים במערכת ההזנה לא ישיפיעו אוטמטית על גרפים של מגמות לאורך זמן. צריך לעשות תמונת מצב לכל השנים עד 2021, לצורך העניין - נעול את 2023 באמצע 2024

**Comment by akariv** [comment]
מעדכן את המערכת כך שהחישוב יבוצע לפי שירותים שהיה להם תקציב בשנת 2021 (השנה הנוכחית לצורך החישוב) ולא לפי הסטטוס פעילות במערכת ההזנה

**Comment by akariv** [comment]
(זה גם עונה על הדרישה של יוני)
