### ISSUE TITLE
הוספת שדה בחירה: אוכלוסיות

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#21]
1. אוכלוסייה כללית
2. חברה ערבית
3. חברה חרדית
4. אנשים עם מוגבלות
5. אנשי מקצוע, מעסיקים וארגונים
6. עולים
7. זרים וחסרי מעמד
8. בני משפחה
9. אחר

**Comment by niryariv** [comment]
@akariv 
להכניס את זה ב״קהלי יעד״ בממשק הניהול?

**Comment by akariv** [comment]
כן
