### ISSUE TITLE
פתיחת טאב חדש בעת שימוש בחלונית החיפוש

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#210]
"לגבי כפתור חיפוש- בבקשה שדף התוצאות ייפתח בלשונית נפרדת כפי שהיה."

תודה

**Comment by akariv** [comment]
מעולם דף התוצאות לא נפתח בטאב חדש - אין בכך הגיון ממשקי (האם מכירים דוגמא
לאתר אחר בו דף התוצאות נפתח בטאב חדש באופן דיפולטי?)

**Comment by emrib** [comment]
אני דווקא חושב שזה נוח במקרה הזה כי החיפוש הוא דריל דאון לשאליתא ספציפית, כשאני צופה בנתונים, אני עדיין ארצה לראות את מבט העל או חיפוש ספציפי נוסף שיפתחו זה לצד זה. החיפוש בכל מקרה זו בקשתו של יוני.

**Comment by akariv** [comment]
דווקא לפני השינוי הנוכחי זה היה אפשרי, כפי שמקובל - לחיצה על הקישור עם Ctrl
היתה פותחת בטאב חדש, לחיצה רגילה באותו הטאב.

**Comment by emrib** [comment]
הנושא חשוב ללקוח וחוזר בכל פגישה, מבחינתי זה לא קריטי בכלל ואם זה הדרישה ניתן לממש:
- לחיצה על כפתור חיפוש תפתח תוצאות בטאב חדש
- כך גם בלשונית החיפוש שנמצאת מעל טבלת הנתונים
- בנוסף (ולא פותח על זה אישיו חדש), שחלונית החיפוש מעל טבלת הנתונים תיראה כמו לשונית החיפוש העליונה (ניתנת להקלדה, ולא כפתור)
- 
תודה

**Comment by emrib** [comment]
תוכל לבצע? תודה

**Comment by emrib** [comment]
מקפיץ .תודה
