### ISSUE TITLE
שינוי הירררכיה עבור מינהל של"ם במשרד הרווחה

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#211]
<img width="265" alt="image" src="https://github.com/hasadna/social-procurement/assets/76155903/e9efa06a-a21c-4973-a416-6a35bade5f60">

תודה

**Comment by akariv** [comment]
אפשר קישור לטקסט ולא תמונה?

**Comment by emrib** [comment]
[- מעדי - היררכיה- שלם  - רכש חברתי.xlsx](https://github.com/hasadna/social-procurement/files/14327691/-.-.-.-.xlsx)


השירות לקהילה, משפחה ושירותים מיוחדים (הוספה מתחת ל"השירות לשיקום נוער")
השירות לטיפול בהתמכרויות ואוכ' מיוחדות (שינוי שם קיים)

**Comment by akariv** [comment]
רק לוודא - ״השירות לקהילה, משפחה ושירותים מיוחדים״ צריך להיות תחת ״קהילה״,
נכון?

**Comment by emrib** [comment]
קיבלתי עוד בקשה לעדכון. וידאתי שאין עוד כדי שנסיים בפעם אחת. לאחר שיפתחו החדשים, היא תעביר שירותים, ותבקש למחוק ענף קיים . להלן:
1. נכון, ״השירות לקהילה, משפחה ושירותים מיוחדים״ צריך להיות תחת ״קהילה״
2. תחת "חוץ ביתי" להוסיף בסדר מעל "דרי רחוב" (באותה רמה של "דרי רחוב"):
       "שירות מסגרות אינטנסיביות"
       "שירות מעברים ורצף טיפולי"

תודה

**Comment by akariv** [comment]
בוצע

**Comment by emrib** [comment]
תודה, בקשה אחרונה באישיו הזה (מקווה):

להעביר תחת תחת אגף משאבי קהילה:
השירות לעבודה קהילתית
השירות להתנדבות

**Comment by akariv** [comment]
בוצע
