### ISSUE TITLE
תצוגת רווחה - תל"מ

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#213]
![image](https://github.com/hasadna/social-procurement/assets/76155903/39d8bf6b-8603-4580-9f0f-b273ba42cfa8)

השירות ללא היררכית אגף "תקוע"

**Comment by akariv** [comment]
יש לשייך את השירות להיררכיה ארגונית:

[image: Screenshot 2024-02-26 at 15.35.19.png]

**Comment by emrib** [comment]
תודה
