### ISSUE TITLE
אין מפעילים ותוקף בהליך רכש מסוג ספק יחיד/פטורים

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#214]
<img width="685" alt="image" src="https://github.com/hasadna/social-procurement/assets/76155903/481ed87d-0aa5-4364-8a05-f5298f9619a9">

יש קשר להליכים שפג תוקפם בחשב הכללי
דוגמא: https://www.socialpro.org.il/i/activities/gov_social_service/shyqvm-nky-npsh-bqhylh-shyrvty-shyqvm-t-svqh-t-svqh-ntmkt-vm-bryt?li=undefined&theme=soproc

**Comment by akariv** [comment]
בנוגע לתוקף - ישנה תקלה בדוחות המפורסמים על ידי מנהל הרכש.

לדוגמא מספר פרסום 613517:
![Screenshot 2024-03-04 at 10 33 11](https://github.com/hasadna/social-procurement/assets/265333/59bff500-6089-4a32-be1d-6a23a4d6bd2a)

מופיע כך בדוח הרשמי (https://mr.gov.il/ilgstorefront/he/news/details/230920201036):

![Screenshot 2024-03-04 at 10 32 42](https://github.com/hasadna/social-procurement/assets/265333/b44635a3-5b7e-49d0-9cd3-ba5ac6098103)

צריך להעלות את הנושא מול מולם (כנראה דרך יוני?)

**Comment by akariv** [comment]
נושא המפעילים תוקן.
