### ISSUE TITLE
  שירות פעיל ומופיע באתר המפתח וממשק ההזנה, אך אין שיוך ליחידה ארגונית כשמורידים אקסל

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#216]
שירותים ללא שיוך ארגוני כשמורדים אקסל בהליכי רכש:
הפקת חומרי הדרכה וביצוע הדרכה לתלמידי החינוך הממלכתי דתי במסגרת תכנית "הרמב"ם לתלמיד"
טיפול בנערות בסיכון במוסדות החמ"ד
מיזם משותף הסוגיה היומית
יום הדרכה משרד החינוך - אתר
ארגון והפעלת תוכניות לשילוב וחשיפת תלמידים בתעשיה
ביצוע פעילויות חדשניות בתחום המדע, הטכנולוגיה והסייבר
מתן שירותי למידה ואמצעים לקיום למידה באמצעות הרשת
הפעלת פרוייקטים חינוכיים לחיזוק וקידום טכנולוגי מדעי במחוזות דרום וצפון
אספקה והפעלת יחידות תוכן לימודי דיגיטלי, ספרים דיגיטליים למוסדות חינוך וסביבות למידה מתוקשבות לגני ילדים וללימודי שפות

**Comment by akariv** [comment]
הכוונה בכותרת האישיו לשירות, לא למכרז, נכון?

**Comment by emrib** [comment]
כן

**Comment by akariv** [comment]
תוקן
