### ISSUE TITLE
שירותים שיש בהם מכרז פומבי פעיל (לא פטור) ללא היקף ותוקף

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#217]
שירותים לדוגמא:
קהילות טיפוליות (מסגרות חוץ ביתיות לנפגעי התמכרויות)
הוסטל טיפולי-שיקומי-תעסוקתי לדרי רחוב
מקלט חירום לנערות וצעירות במצבי סיכון
מסגרת חוץ ביתית לטיפול באנשים בוגרים עם שילוב של התנהגויות מיניות יחד עם אינטליגנציה גבולית
תוכנית ענ"ן - עסקים נתמכי נכים - תעסוקה לאנשים עם מוגבלויות

**Comment by akariv** [comment]
@emrib 
לא הבנתי מה זה ״מכרז פומבי ללא היקף״  - איפה רואים את ההיקף?

לגבי התוקף:
- מקלט חירום לנערות וצעירות במצבי סכנה: לכל המכרזים מופיע תוקף חוץ מאחד שעבורו המידע הזה לא הוזן
- הוסטל טיפולי-שיקומי-תעסוקתי לדרי רחוב: כנ״ל
- מסגרת חוץ ביתית לטיפול באנשים בוגרים עם שילוב של התנהגויות מיניות: כנ״ל

לא בדקתי את השאר אבל נראה שברור מה מקור הבעיה.

**Comment by emrib** [comment]
תודה
