### ISSUE TITLE
קו תקציב מאושר לא נראה כאשר הוא חופף לתקציב ביצוע

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#218]
דוגמאות לפי שם שירות עם בדיקה של נתונים ממשק הזנה:

**מרכזי חוסן**

**מעונות פנימייה לאנשים עם מוגבלות** - אמנם יש בעיית הזנת תקציב גבוהה מתקנה ב2020 ו2021, אך התקציב המאושר לא מוצג גם לשנים קודמות.

**מעונות פנימייה לאנשים עם מוגבלות** - מוצג רק החל משנת 2020

**מית"ר כוללני (מרכז יום רב תחומי) לבני נוער במצבי סיכון** 

**ישיבות נוח"ם** - בעיה בשנה אחת לגבי חריגה ביחס לגובה תקנה

**Comment by akariv** [comment]
מרכזי חוסן - הביצוע שהוזן זהה לתקציב המאושר בכל השנים, על כן הגרף מראה רק קו אחד (שני הקווים חופפים לחלוטין). זו בעיית הזנה כי הביצוע בפועל לא יכול להיות זהה לגמרי לתקציב (מה גם שביצוע המדווח בספר התקציב הוא נמוך יותר מזה
שהוזן ידנית).

מעונות פנימייה לאנשים עם מוגבלות - אותו הסיפור, עשו העתק-הדבק לתקציב המבוצע לתוך המאושר. תקציב מאושר הוא בד״כ בכפולה של אלפי שקלים, ולא ברמת האגורות...  הגרף עצמו מתחיל ב-2017 ולא מ-2020 כפי שכתבת.

מית"ר כוללני (מרכז יום רב תחומי) לבני נוער במצבי סיכון - אותו הסיפור

ישיבות נוח"ם - אותו הסיפור

ההתראות המופיעות במערכת ההזנה לא משפיעות בשום צורה על שום דבר, הן רק שם בשביל להתריע בפני המזינים שייתכן שיש טעות...

**Comment by emrib** [comment]
תודה, אמשיך לבדוק כשאחזור אם אכן אלו דוגמאות מייצגות. בכל מקרה זה אישו לשיפור עיצוב בהזדמנות
