### ISSUE TITLE
לא ניתן לשמור שירות פעיל ל2023 בעל תקציב תוספתי מ2022 

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#219]
שם השירות: תכנית נור לנערות וצעירות בחברה הערבית

לא קיים עבורו תקציב ל2023, הוא ניזון מתקציב 2022. המערכת לא מאפשרת לשמור ולסמן כהושלם.

**Comment by akariv** [comment]
יש להזין את התקנה התקציבית שקיימת ב2023 ממנה יוצא התקציב

**Comment by emrib** [comment]
התקציב ניתן מיתרות 2022. אין תקצוב ב2023
בנוסף, הדבר נכון גם ל2017 לה לא הוזן תקציב.
התקנות קיימות בשירות
![image](https://github.com/hasadna/social-procurement/assets/76155903/52b134c5-7e4c-4b16-94b1-894773872088)

**Comment by akariv** [comment]
אז אפשר למחוק את השורות המיותרות ולשמור.

**Comment by emrib** [comment]
ביצעתי את זה שוב ושמרתי. למרות זאת התקציב חוזר להופיע ריק. בדשבורד מופיע כהושלם ברמת השירות, אך ברמת המדד מופיע כיש להשלים נתונים לשנה זו. (תכנית נור)

![image](https://github.com/hasadna/social-procurement/assets/76155903/ddd6ed0b-5973-430b-88aa-ab3808348567)

**Comment by akariv** [comment]
למרות שאני לא חושב שיש דבר כזה (פעילות ממשלתית שפועלת בלי תקציב), הזנתי אפסים בתקציב 2023 ושמרתי.
