### ISSUE TITLE
אי התאמה בין סטטוס הזנה לחיווי סטטוס

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#221]
**שירות תחנות מידע וייעוץ ללקויי ראייה**
------------------------------------------------------------------------------------------------------------------------------------------------------
צילום מסך של יוני ומלל שמתאר את הבעיה מבחינתו:
![image](https://github.com/hasadna/social-procurement/assets/76155903/82beb297-928e-489c-a98b-9a1e5f511681)

- היו נתונים מ2017 עד 2021
- השירות הופיע בסטטוס ירוק בהיר (נדרש עדכון לשנה זו) למרות שלא הופיעו נתונים ל2023 (אני לא רואה בזה בעיה כל השירות מסומן כפעיל)
- ברגע ששונה הסטטוס ידנית לכתום (ההזנה טרם הושלמה), ניתנה אינדיקציה כאילו יש נתונים ל2023 (צילום מסך למעלה)
------------------------------------------------------------------------------------------------------------------------------------------------------
שאלות:
- בינתיים הושלמו הנתונים לשירות זה והוא מופיע כירוק כהה (הושלם)
- מה ההסבר להתנהגות הזו? האם ניתן לקבל את הלוגיקות של הגדרת הסטטוס? (חיפשתי בתיקיית הפרויקט איפיון לזה ולא מצאתי)
- האם זה באג?

**Comment by akariv** [comment]
כתום = השירות נשמר כ״עדיין בעבודה״
ירוק בהיר = השירות נשמר כ״הושלם״ אבל חסרים נתונים לשנה הנוכחית
ירוק כהה = השירות נשמר כ״הושלם״ ויש את הנתונים לשנה הנוכחית

אדם

**Comment by emrib** [comment]
נראה אם זה חוזר, ואם כן אפתח שוב אישיו. מבין שאין כאן באג עם הסוגיה של "2023"

**Comment by akariv** [comment]
לא הבנתי מה אמור לחזור - זה התנהג בדיוק כמו שפירטתי, לא?
