### ISSUE TITLE
לוודא שלא רואים בפרונט: מעונות פנימייה לאנשי עם מוגבלות

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#222]
- מעונות פנימייה לאנשים עם מוגבלות
- אומנת חירום

**Comment by akariv** [comment]
השרות סומן כשרות לא פעיל.

**Comment by akariv** [comment]
https://data-input.obudget.org/he/datarecords/social_service/m-vnvt-pnymyyh-lnshym-m-mvgblvt

**Comment by emrib** [comment]
תודה רבה

**Comment by akariv** [comment]
מה נדרש ממני כאן @emrib ?

**Comment by emrib** [comment]
להסביר טכנית איך שירות שסומן כלא פעיל נראה בפרונט

**Comment by akariv** [comment]
כי יש לו תקציב ל-2023 ואמרנו שאנחנו לא מתייחסים לסטטוס פעיל/לא פעיל בהחלטה
אם להציג את השירות.

**Comment by akariv** [comment]
אפשר לסמן את השירות כ״עדיין בעבודה - לא לפרסום״ אם רוצים לא להציג אותו.

**Comment by emrib** [comment]
קיבלתי

**Comment by emrib** [comment]
תוכל לעשות הרצה שאני אוודה שזה תקין? תודה
