### ISSUE TITLE
שאילתות רידאש

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#226]
גם אם זה אד הוק לבדיקות הנתונים

**Comment by akariv** [comment]
אם הבנתי נכון את השאלה, אנחנו לא שומרים עותקים של המידע כפי שהוא היה לפי שנה או שנתיים.

**Comment by emrib** [comment]
לא הסברתי את עצמי טוב. אני רוצה לערוך בדיקה של השירותים וזיהוי שירותים בהם יש שינוי חד במס' מפעילים או תקציב בין 2022/3 ל2021 או מוקדם יותר. לשם כך, הייתי רוצה טבלת אקסל גולמית לפי טאב "שירותים", רק שכוללת גם את נתוני השנים הקודמות

**Comment by akariv** [comment]
אפשר לייצר שאילתה כזו ברידש.

**Comment by emrib** [comment]
תוכל לייצר/להדריך אותי איך עושים? שינוי חד = דלתא של 15% או יותר בגידול/קיטון של מס' מפעילים/תקציב ביצוע בשנת 2023 ביחס ל2021.

**Comment by emrib** [comment]
מקפיץ את השאלה הזו. תודה

**Comment by emrib** [comment]
1. לפי שירות, שינוי (אחוזים ומספר אבסולטי) בתקציב בין 2021 ל2022, בין 2022 ל-2023 ובין 2021 ל2023
2. לפי שירות, שינוי (אחוזים ומספר אבסולטי) במס' מפעילים בין 2021 ל2022, בין 2022 ל-2023 ובין 2021 ל2023
3. לפי מינהל, שינוי (אחוזים ומספר אבסולטי) במספר השירותים בין 2021 ל2022, בין 2022 ל-2023 ובין 2021 ל-2023

האם ניתן לייצא מהרידאש?

**Comment by emrib** [comment]
מוסיף: אם ניתן גם שינוי בפרמטר של שינוי מוטבים לפי שירות באופן דומה

**Comment by akariv** [comment]
שינויים בתקציב/מוטבים, לפי שירות
https://redash.hasadna.org.il/queries/1388/source?p_COMPARE_NEW_YEAR=2023&p_COMPARE_PREV_YEAR=2022&p_FIELD=beneficiaries&p_SUBFIELD=num_beneficiaries

שינויים בתקציב/מוטבים, לפי מנהל
https://redash.hasadna.org.il/queries/1393/source?p_COMPARE_NEW_YEAR=2023&p_COMPARE_PREV_YEAR=2022&p_FIELD=manualBudget&p_SUBFIELD=approved

לשתי השאילתות ממלאים 4 שדות:
- COMPARE_NEW_YEAR: השנה הנוכחית להשוואה
- COMPARE_PREV_YEAR: השנה הקודמת להשוואה
- manualBudget/beneficiaries: מה רוצים להשוות, תקציב או מוטבים?
- approved/executed/num_beneficiaries: השדה להשוואה - תקציב מאושר, מבוצע או מספר מוטבים

אשלח את שאילתות מספר המפעילים בהמשך

**Comment by emrib** [comment]
תודה רבה

‫בתאריך יום א׳, 16 ביוני 2024 ב-11:15 מאת ‪Adam Kariv‬‏ <‪
***@***.***‬‏>:‬

**Comment by akariv** [comment]
המפעילים - לפי שירות:

https://redash.hasadna.org.il/queries/1394/source?p_COMPARE_PREV_YEAR=2022&p_COMPARE_NEW_YEAR=2023
