### ISSUE TITLE
לא נמצאו הפטורים הבאים במערכת

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#227]
-  "שירותי העברה וליווי בכפייה במחוז אילת" | מס' פרסום 4000568530 
- "המרכזים הרפואיים יוספטל וסורוקה - הפעלת מרכז אקוטי לטיפול בנפגעי/ות תקיפה מינית" | מס' פרסום 4000561922

**Comment by akariv** [comment]
נראה שמנהל הרכש הנבלות החליפו את הקישור לדוח הפטורים שלהם כך שבמקום שיהיה
קישור להורדת קובץ אקסל, זה קישור ל-bit.ly שמפנה לתיקייה של גוגל דרייב בה
אפשר למצוא קובץ zip אשר מכיל קובץ אקסל.

**Comment by emrib** [comment]
אז מה עושים בהיבט המערכת? זה פתיר טכנית? בכל מקרה אציף ליוני

**Comment by akariv** [comment]
כן, פתיר, עובד על זה עכשיו.

סתם מעצבן.

**Comment by emrib** [comment]
סטטוס: 

- אדם פתר את הבעיה
- בדיקות ע"י משתמשים ועדכון שאכן תקין
