### ISSUE TITLE
הורדת גרף לא עובדת

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#228]
https://next.obudget.org/api/download?format=xlsx&filename=%D7%9E%D7%A4%D7%AA%D7%97%20%D7%9C%D7%A8%D7%9B%D7%A9%20%D7%94%D7%97%D7%91%D7%A8%D7%AA%D7%99%20%2F%20%D7%9E%D7%A9%D7%A8%D7%93%20%D7%94%D7%A8%D7%95%D7%95%D7%97%D7%94%20%2F%20%D7%9E%D7%99%D7%93%D7%A2%20%D7%A2%D7%9C%20%D7%AA%D7%A7%D7%A6%D7%99%D7%91%20%D7%9C%D7%90%D7%95%D7%A8%D7%9A%20%D7%96%D7%9E%D7%9F&headers=%D7%9E%D7%A9%D7%A8%D7%93%3B%D7%A9%D7%A0%D7%AA%20%D7%AA%D7%A7%D7%A6%D7%99%D7%91%3Cyear%3B%D7%AA%D7%A7%D7%A6%D7%99%D7%91%20%D7%9E%D7%90%D7%95%D7%A9%D7%A8%3Cvalue%3B%D7%AA%D7%A7%D7%A6%D7%99%D7%91%20%D7%91%D7%99%D7%A6%D7%95%D7%A2%3Cvalue2

![image](https://github.com/hasadna/social-procurement/assets/76155903/61fa7771-0480-4ab3-a4bd-c7838176fa4a)

**Comment by akariv** [comment]
תגלה לי איזה גרף זה היה?

**Comment by emrib** [comment]
זה היה כמה גרפים זה היה דוגמא עבור גרף זה: 
![image](https://github.com/hasadna/social-procurement/assets/76155903/947614d5-b74f-4b16-82ce-608879f3b218)


אבל שניסיתי שוב עכשיו - זה עבד. סוגר אישיו

**Comment by akariv** [comment]
כן, תיקנתי הבוקר.
