### ISSUE TITLE
פער בנתונים היסטוריים (2021 ואחורה) בין מצב קיים למצב טרום הזנת נתוני 22-23

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#230]
**לפגישה** 

לפי יוני יש פערים משמעותיים ביחס לנתונים שבידיו לגבי 2021 (צילומי מסך לעומת מצב קיים במערכת):

- משרד החינוך 1,740 מלש"ח לעומת 1,046 מלש"ח
- משרד הבריאות 4,821 מלש"ח לעומת 4,783 מלש"ח
- משרד הרווחה 5,310 מלש"ח לעומת 3,370 מלש"ח 

האם זה באג?

**Comment by akariv** [comment]
האם שירותים שהיו פעילים ב2021 סומנו כלא לפרסום?
האם שונו רטרואקטיבית נתוני התקציב של 2021?

**Comment by emrib** [comment]
אבדוק מולם (יותר קל להוציא מים מהסלע), בכל מקרה יש משהו טכני שהיה יכול לגרום לזה או משהו אחר שמוכר לך?

**Comment by emrib** [comment]
סטטוס 10/6:

- אמרי יוודא מול מובילי רכש סטטוס שירותים שהוגדרו כ"לא לפרסום"
- במידת הצורך אדם יממש דוח DIFF בין מאי 2023 למצב נוכחי של שנת 2017-2021

**Comment by emrib** [comment]
מעדכן סטטוס:

1. כמה זמן להערכתך הכנת דוח DIFF? לאור הקושי מול המובילים אני שוקל כן לעשות. 

2. מבקש לוודא:
**"לא לפרסום"** -> כל נתוני השירות נגרעים מהתצוגה באתר, כולל היסטוריה
**"לפרסום" (פעיל)** -> כל הנתונים באתר, כולל היסטוריה
**"לפרסום" (פעיל, אבל ללא נתונים לשנת תקציב כל שהיא)** -> כל הנתונים באתר, כולל היסטוריה, אבל ללא הצגת השנה/נים ללא התקציב
**"לא פעיל** -> נתונים באתר, אבל רק עבור טאב בתצוגת טבלה של הליכי רכש ומפעילים
**יש אפשרות נוספת ששכחתי?**

**Comment by akariv** [comment]
https://docs.google.com/spreadsheets/d/1vgluJKkSBMQhW_LDHuFKYsK29F0n57cwK1PkCWOUf-g/edit?gid=1888199296#gid=1888199296

הדוח יחסית כוללני, כרגע מופעל סינון לשירותים המסומנים כ״לא לפרסום״ שלא היום כך בספטמבר (או להיפך).

**Comment by emrib** [comment]
מבקש דוח זהה רק לנתונים עכשווים (ביחס לספטמבר 23). תודה

**Comment by akariv** [comment]
הוספתי כגליון חדש לאותו הגוגל-דוק
