### ISSUE TITLE
חיווי לסטטוס הזנת שירות במערכת

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#232]
תיאור הבעיה:
כיום לא ניתן לדעת מה הסטטוס הקיים של שירות בעמוד השירות עצמו, אלא רק בדשבורד.
בפרט, תחת סטטוס "בעבודה" כפי שמופיע בכתום חזק בדשבורד לא ניתן לדעת אם השירות פורסם או לא פורסם.
מצב זה בעייתי משום שהמשתמש חושש ללחוץ על שינוי סטטוס הזנה למטה (אינו יודע מה הסטטוס כיום - באתר או לא, ואז צריך לבדוק נקודתית באתר)

פיתרון מוצע:
הוספת כיתוב "סטטוס" תחת "תיאור השירות ובו פירוט סטטוס ההזנה הקיים.
למשל: פעיל, נתונים חסרים, מפורסם באתר

**Comment by akariv** [comment]
בוצע
