### ISSUE TITLE
התייחסות לדוחות בקרה

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#233]
ראה קובץ מצורף:

1. איזה דוח חסר אתה ממליץ להוסיף ?
2. האם השדות "תיאור" ושדה "מקור מסד הנתונים" בעלי ניסוח מדוייק עבור הרשומות ? 
3. האם keep private זה "לא לפרסום" ? 

[240616 - דוחות רכש חברתי.xlsx](https://github.com/user-attachments/files/15861321/240616.-.xlsx)
(קובץ קצת ערוך ביחס למה ששלחתי בהודעה לפני עריכה)

**Comment by emrib** [comment]
בהקשר סעיף 3 למעלה, האם זה מכסה אותי לגבי דוח שירותים בסטטוס "לא לפרסום"? אם לא, האם תוכל לייצר כזה שכולל את ההיררכיה המשוייכת לשירות (משרד, מינהל, אגף, יחידה)?

**Comment by emrib** [comment]
בדוח 15, מה המשמעות של זה? 
![image](https://github.com/hasadna/social-procurement/assets/76155903/909619f3-300c-49c3-9382-619ed1e06724)

**Comment by akariv** [comment]
אני חושב שהדוחות שלך מכסים את כל מה שקריטי.
לגבי 3 - אכן, keepPrivate = לא לפרסום
כך, אם זה לא הוגדר ב-old ו-TRUE ב-new זה שירות שהיה לפרסום ב2023 ועכשיו מוגדר כלא לפרסום

**Comment by emrib** [comment]
תודה
