### ISSUE TITLE
במערכת ההזנה מופיע בדשבורד "נדרש עדכון..." אבלרמת אגף מסוים, אבל תחת האגף השירותים כולם ב"הסתיים" ולכולם יש נתונים 2023

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#234]
משרד הבריאות
חטיבת רפואה
האגף לבריאות הנפש
טיפול באוכלוסיות מיוחדות

**Comment by akariv** [comment]
החישוב הסתכל במקומות מסוימים על השנים בהם הוזן תקציב ומספר המוטבים במקומות אחרים רק על התקציב ובמקום אחר על שדות אחרים... בנוסף לא תמיד בדקנו שהמספר שהוזן הוא לא 0 (מסתבר שכמה חוכמולוגים מצאו דרך ״לעקוף את השיטה״)

סידרתי כך שבכל המקומות הדרישה היא שיוזן תקציב + מוטבים לשנת 2023.
