### ISSUE TITLE
תיאור הבעיה שהיתה בשכבת התצוגה

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#235]
תוכל לאשר ולפרט את הבעיה שהיתה בשכבת התצוגה?

לאחר טיפול בסוגיות הזנת נתונים במינהל מוגבלויות הקשורות בסטטוס שירות ("לא לפרסום" ואיחוד תקציב שירותים שונים), התברר שעדיין יש בעיה בגרפים האגרגטיביים שבאתר. הסתבר שהיתה בעיה טכנית שטופלה ותוקנה רוחבית.

**Comment by akariv** [comment]
מאחורי כל גרף יש שאילתה ל-database המשמשת לאחזור הנתונים המוצגים.

בשאילתה של גרף התקציב לאורך זמן (וגם בגרף היסטורי אחר), גיליתי שהופיע פרמטר אשר הגביל את השאילתה רק לשירותים הפעילים כרגע. 
מכיוון שלא מעט שירותים ״הוצאו לגימלאות״ בהזנה האחרונה, זה השפיע על האגרגציה של השנים הקודמות.


שינוי השאילתה אפשר לה לסכם את המידע של כלל השירותים (גם אלו שכבר לא פעילים השנה).
