### ISSUE TITLE
שינוי צבעי קוי מגמה דומים

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#236]
במינהל מוגבלויות במשרד הרווחה –   הערכה הכרה ותכניות VS חוץ ביתי 
במינהל הפדגוגי במשרד החינוך - חינוך ילדים ונוער בסיכון VS שרות פסיכולוגי ייעוצי

**Comment by emrib** [comment]
מקפיץ. תוכל לטפל בזה ? תודה

**Comment by emrib** [comment]
צבע כתום בשני קווי מגמה תחת רווחה->מוגבלויות-> תקציב לאורך זמן
בנוסף, ביקשו מאיתנו להחליף את השחור שבחינוך -> מינהל פדגוגי - תקציב לאורך זמן

תודה

**Comment by akariv** [comment]
duplicate of #249
