### ISSUE TITLE
הוספת שדה בחירה: סוג מכרז

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#24]
פומבי - רגיל / מסגרת / מאגר
פטור- מיזם משותף / ספק יחיד

**Comment by niryariv** [comment]
@ShiraTza יש עוד אפשרויות לפטור?

**Comment by ShiraTza** [comment]
סיבות לפטור ממכרז: 
    א. הארכת התקשרות
    ב. הרחבת התקשרות
    ג. ספק יחיד
    ד. התקשרות עם רשות מקומית
    ה. מיזם משותף
    ו. אחר

**Comment by akariv** [comment]
תנו בבקשה את הערכים כפי שהם מופיעים במערכת נעמ״ה, אין לנו אפשרות לנחש את
הסוג אם הוא לא מופיע במקור.

**Comment by niryariv** [comment]
@ShiraTza

**Comment by niryariv** [comment]
מוחק לטובת #47
