### ISSUE TITLE
בקשה לדוח רידאש חדש - ביצוע תקציב בפועל ביחס לתקציב מאושר

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#244]
"שנה"
"תקציב ביצוע בפועל" 
"תקציב מאושר" 
"תקציב ביצוע בפועל" ביחס ל"תקציב מאושר" 

האם ניתן להוסיף באותו דוח השוואה של המדד ביצוע הנ"ל במספר שנים?
הכוונה להשוות את הביצוע לשנה אחרת כדי לתת מושג מה היתה מידת המימוש של התקציב בשנים קודמות  ובכך "לחוש" את הנתונים

**Comment by akariv** [comment]
האם מדובר על נתוני התקציב שהוזנו ידנית, או על נתוני התקציב של התקנות התקציביות המשויכות לשירות כפי שנמשכו מספר התקציב?

**Comment by emrib** [comment]
שהוזנו ידנית.

**Comment by akariv** [comment]
https://redash.hasadna.org.il/queries/1412#1614

שדה anomaly כולל מספר המייצג עד כמה השורה הזו יוצאת דופן לעומת שאר השורות של אותו השירות (0 = לא יוצא דופן כלל).

**Comment by emrib** [comment]
תודה
