### ISSUE TITLE
שינויי היררכיה - שח"א

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#247]
**מסכם כאן השינויים המבוקשים לאחר ההתכתבות:**

**1.      שירותים למחיקה:**
a.       אומנה - אומנת חירום (חלק משירות האומנה "הרגילה" – גם מהותית וגם במכרזים המצויינים באומנה)

b.      רווחת הילד והמשפחה - השביל המיטיב – נכלל בשירות שניתן בתוכנית נושמים, אין סיבה שיופרד משם.

c.       התנדבות - שירות לאומי אזרחי (מדובר על בניית תשתית ולא על שירות שמתמקד במתן שירות ישיר)

d.      התנדבות - הרשת להתנדבות ישראלית (מדובר על בניית תשתית ולא על שירות שמתמקד במתן שירות ישיר)

e.       התנדבות - מיזם משותף לפיתוח התנדבות נקודתית ברשויות מקומיות (מדובר על בניית תשתית ולא על שירות שמתמקד במתן שירות ישיר)

f.        מה שאומר שכרגע אפשר להוריד לגמרי את השירות להתנדבות (או להשאיר ריק למקרה שבשנה הבאה יתווסף משהו. בכל מקרה צריך להיות "השירות להתנדבות")

g.       חוק - יחידה טיפולית ייעוצית (זה חלק ממרזי חירום וניתן מאותו המכרז

h.      אחר – תוכנית אוריינות דגיטלית (לא רכש חברתי, אין שירות ישיר)  שאלה לאופיר: האם כשכתבת "רק פיתוח הכלים הדיגיטליים." התכוונת ל"תוכניות אוריינות דיגיטלית" ? אפשר להשאיר את "אחר" ומה שתחתיו ללא שינוי

i.         תחום לוועדות ערר – למחוק, לא רלוונטי לרכש חברתי

**2.     שינויי היררכיה בהתאם למבנה ארגוני**

a.       חוץ ביתי = "אגף בכיר חוץ ביתי והשמות מיוחדות"

b.      אין "קהילה" אלא - אגף בכיר משפחות ילדים ונוער בקהילה שמכיל את השירותים: שירות הגנה וטיפול  במצבי טראומה ומשבר, השירות לרווחת המשפחה והילד, תוכניות טיפול במשפחה ובילד (שירות שכרגע אין רכש חברתי תחתיו, אפשר אולי להכניס ושיהיה ריק למען הסדר)

c.       חוק: צריך להיות "חוק הנוער" וזה צריך להיות תחת אגף בכיר משפחות ילדים ונוער בקהילה

d.      אין "קהילה" אלא "אגף בכיר משאבי קהילה" שמכיל את השירות להתנדבות (שאמור להיות ריק כרגע), השירות לעבודה קהילתית

e.       אחר: אמור להיקרא: אגף תעסוקה לאוכלוסיות רווחה

תחת אחר כרגע יש את תוכנייו האוריינות הדיגיטלית - רק אותה צריך להשאיר תחת אחר.
שאר התוכניות תחת אחר צריכות להיות תחת אגף תעסוקה שכן צריך לפתוח.

**Comment by akariv** [comment]
זה המצב כרגע בשח״א - לדעתי כל השינויים המופיעים פה כבר יושמו.

![Screenshot 2024-09-23 at 15 08 21](https://github.com/user-attachments/assets/851e1a01-5dc1-4906-8517-e471681c75ee)

את השירותים השייכים לשח״א יש לפתוח, לערוך ולשייך ליחידה הארגונית הרלוונטית.
