### ISSUE TITLE
airtable interface to jotforms?

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#248]
מה דעתך? 
יש סיבה למה לא לעבור לגוטפורמס?

**Comment by akariv** [comment]
כי אז כל מילוי של הטופס יצור שורה חדשה באיירטייבל ולא יהיה אפשר לערוך, כפי שהופיע בדרישות המקוריות

**Comment by emrib** [comment]
אז הברירה היא בין איירטיבל שהממשק מענה פחות נוח, בטח כשעושים בעמוד אחד ארוך, לבין גוטפורמס שהחיסרון הוא שעדכון סקר יחייב דריסה של כל התשובות ולא שינוי מענה ספציפי? עוד משהו?

אני חושב שגוטפורמס זה הרע במיעוטו

חוצמזה, ייתכן ויש לפי GPT, אבדוק מחר:
איך לאפשר עריכת תשובות לאחר הגשה ב-JotForm:
יצירת טופס עם הגדרה לעריכת תשובות: כשאתה בונה את הטופס, ודא שהפעלת את האפשרות לעריכת תשובות על ידי המשתמשים.
שליחת לינק לעריכת התשובות: כדי שמשתמשים יוכלו לערוך את התשובות שלהם לאחר ההגשה, עליך להוסיף "ערוך קישור" למייל האוטומטי שהם מקבלים לאחר ההגשה. כך הם יוכלו לחזור ולערוך את תשובותיהם:
לחץ על Settings בתוך JotForm.
תחת הכרטיסייה Emails, ערוך את התבנית של המייל שנשלח לאחר ההגשה.
הוסף את המילה {edit_link} בתוך גוף המייל. פעולה זו תאפשר למשתמשים לערוך את תשובותיהם לאחר ההגשה דרך הלינק שיקבלו במייל.
דגשים:
משתמשים יוכלו לערוך את תשובותיהם רק דרך הלינק שיקבלו במייל ולא ישירות דרך הטופס.
ודא שמנהל הטופס הגביל או לא הגביל את עריכת התשובות בהתאם לצורך.
לפרטים נוספים, תוכל לעיין בתמיכה של JotForm: JotForm - How to Let Users Update Their Submissions
