### ISSUE TITLE
צבע גרפים

### ISSUE THREAD

**Issue by emrib** [hasadna/social-procurement#249]
במינהל מוגבלויות במשרד הרווחה –  בגרפים לא ניתן להבדיל בין הערכה הכרה ותכניות וחוץ ביתי היות ששניהם באותם הצבעים.

+ (לא באג, אלא בקשת הלקוח) -> האם יש צבע אחר בגרף במקום שחור תחת מינהל פדגוגי ל"שירות פסיכולוגי ייעוצי"?

**Comment by emrib** [comment]
מצורף פירוט של התאמת צבעים מבוקשת ע"י משרד צוות רכש חברתי:
[התאמת צבעים.docx](https://github.com/user-attachments/files/18112910/default.docx)
[בחירת פלטת צבעים לאתר המפתח של רכש חברתי.pptx](https://github.com/user-attachments/files/18112911/default.pptx)

**Comment by akariv** [comment]
לא ממש ברור מה מבקשים לעשות פה.

כרגע יש סכמת צבעים בהם נעשה שימוש בגרפים עצמם.
אין התאמה ספציפית של צבע לסדרה בגרף, בין השאר כי שמות הסדרות הן דינמיות ונקבעות על ידי המזינים - למשל, שמות האגפים ותתי האגפים).

במסמך המצורף יש צד אחד סכמה, ומצד שני התאמה (חלקית) של שמות הסדרות לצבעים. 

למה עלי להתייחס?

**Comment by emrib** [comment]
אפשר להחליף סקאלת צבעים בלבד, ללא התאמה לסדרות, ואז השיוך התבצע כפי שהוא מתבצע כיום?

**Comment by akariv** [comment]
לא משנה, כבר מימשתי לפי הבקשה שלהם...

**Comment by emrib** [comment]
תודה
