### ISSUE TITLE
להפוך שדות שם משרד / שיוך ארגוני לתפריט בחירה

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#25]
לפי ההיררכיה הארגונית ב #16 

![Screen Shot 2021-01-11 at 15 02 15](https://user-images.githubusercontent.com/1771/104185743-0dab1500-541e-11eb-93de-a7d0fc03cfbc.png)

**Comment by niryariv** [comment]
נראה שהשדות של שיוך ארגוני נעלמו מהממשק?
![Screen Shot 2021-01-19 at 13 13 52](https://user-images.githubusercontent.com/1771/105027250-35226300-5a58-11eb-85cf-061734a3af27.png)

**Comment by akariv** [comment]
לינק?

**Comment by akariv** [comment]
כן, אני רואה - יתוקן

**Comment by akariv** [comment]
עכשיו בסדר

https://data-input.obudget.org/he/datarecords/social_service/t-svqh-ntmkt
