### ISSUE TITLE
צמצום תקנות אפשריות

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#26]
כרגע ממשק חיפוש תקנה במסך עריכת שירות חברתי מציג תקנות מכל השנים, יכול להיות שכדאי להגביל רק לשנים מ 2016 והלאה (שמאז יש ספרי רכש) כדי לצמצם אפשרויות?

**Comment by akariv** [comment]
אני לא מסכים - אפשר לחבר תקנות היסטוריות לשירותים.
 גם אם הספר הראשון פורסם רק ב-2016, השירותים לא התחילו ב-2016.

**Comment by niryariv** [comment]
הכוונה שלך שאולי נרצה ליצור ספר רכש ל 2010 (לדוגמא) או שיכול להיות מצב שתקנה מ 2010 תקושר לשירות חברתי מ 2016? המטרה במשימה היא לסנן תקנות לא רלבנטיות אבל אם תקנה ישנה יותר יכולה להיות רלבנטית כמובן צריך להשאיר אותה. יכול להיות שאפשר לקבוע סף של שנה שממנה והלאה מציגים תקנות?

**Comment by akariv** [comment]
כן, שירותים שמקושרים לתקנה יקושרו גם להיסטוריה של התקנה (טרום 2016).
בכל מקרה מוצגת רק השנה האחרונה עבור כל תקנה.
