### ISSUE TITLE
להציג מספר מוטבים ותקציב כפי שיובאו מספר הרכש במסך עריכת שירות חברתי

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#27]

**Comment by niryariv** [comment]
@akariv אני רואה מספר מוטבים אבל לא תקציב

**Comment by akariv** [comment]
התקציב נגזר מהתקנות התקציבית

**Comment by niryariv** [comment]
מה קורה במצבים שהתקנה מכסה יותר מאשר הסעיף הספציפי (או שהוא ניזון מכמה תקנות), כלומר התקציב של הסעיף שונה מתקציב התקנה?

**Comment by akariv** [comment]
אפשר לציין מספר תקנות לכל שירות או לציין שתקנה משתתפת באחוז מסוים מתוכה
(נגיד - 50%).
