### ISSUE TITLE
חיווי ברור במחיקת תקנה מקושרת

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#28]
היום התקנה נמחקת באופן שקשה להבחין בו. ממשק מוצע: עם לחיצה על כפתור ״מחיקה״ צבע התקנה הופך אפור, מופיע כפתור ״בטל מחיקה״

**Comment by akariv** [comment]
זה ישאיר הרבה זבל על המסך, לא?

**Comment by niryariv** [comment]
כל זמן שזה לא במרכז זה פחות מפריע לדעתי. המטרה היא (1) משוב שהמחיקה בוצעה (2) אפשרות מהירה לתקן מחיקה בטעות

**Comment by niryariv** [comment]
זה קיים? (ראה #67)

**Comment by akariv** [comment]
הוספה תיבת דיאלוג סטנדרטית למניעת מחיקה שגויה.

**Comment by niryariv** [comment]
ויש אפשרות לבטל את המחיקה? (אני לא בודק כי לא רוצה למחוק תקנה בלי שאוכל להחזיר :)

**Comment by akariv** [comment]
פשוט מוסיפים שוב את התקנה

**Comment by niryariv** [comment]
טעות שלי חשבתי על שירות במקום תקנה.. סוגר
