### ISSUE TITLE
 מחיקת שירות חברתי

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#29]
1. הכפתור צריך להופיע באדום ורחוק יותר מ״שמירת שירות חברתי״ כדי למנוע בלבול
2. אחרי שהמשתמש לחץ על הכפתור, השרות צריך להופיע ברשימת השירותים של המשרד כמחוק ולידו כפתור לביטול הפעולה והחזרת השירות למשרד

**Comment by akariv** [comment]
אז לא תהיה דרך למחוק שירות חברתי לחלוטין?

נראה לי שעדיף להוסיף שלב של ״האם אתם בטוחים שתרצו למחוק את ...״ ואז פשוט למחוק, לא?

**Comment by niryariv** [comment]
אפשרות אחרת, להוסיף ליד שרותים מחוקים כפתור של ״מחק לתמיד״, או למחוק אותם אוטמטית לתמיד אחרי זמן מסוים. הרעיון הוא לאפשר תיקון טעות. מנגנון של ״האם אתה בטוח״ פחות אפקטיבי כי יכול להיות שהטעות תתברר ככזו רק אחרי זמן

**Comment by akariv** [comment]
> למחוק אותם אוטמטית לתמיד אחרי זמן מסוים

יכול להיות שהטעות תתברר ככזו רק אחרי זמן

> שרותים מחוקים כפתור של ״מחק לתמיד״

פשוט יהפוך את התהליך לכזה של שני קליקים, זהה לדעתי לדיאלוג של ״האם אתה
בטוח״... בסוף אם מישהו עושה טעות אז הוא יעשה טעות.

האפשרות הסבירה מבחינתי היא לחסום את אפשרות המחיקה שתהיה זמינה רק לאדמינים,
כך שהתהליך תמיד ידרוש שני אנשים (איש הרכש שפונה לאדמין בשביל למחוק).

**Comment by niryariv** [comment]
נשמע לי שזה קצת מסבך את התהליך ואת חווית המשתמש, אבל אפשר להתיעץ עם המשתמשים כשנדבר איתם

**Comment by niryariv** [comment]
מה דעתך על ההליך הבא:

1. משתמש מסמן למחיקה
2. מכניס סיבה למחיקה (לפי משוב מעדי)
3. השירות עובר לסטטוס ״מומלץ למחיקה״ (מופיע בטקסט אפור במסך הראשי, ו/או תחת רשימה נפרדת של מחוקים)
4. משתמש ברמת אדמין יכול למחוק לגמרי

**Comment by niryariv** [comment]
אחרי מחיקת שירות חברתי, הוא עדיין נשמר במערכת, כלומר יש לנו יכולת לשחזר אותו? אם כן אז פשוט נעזוב את זה בינתיים ונראה כמה נפוץ המקרה שמוחקים שירות

**Comment by niryariv** [comment]
> מה דעתך על ההליך הבא:
> 
>     1. משתמש מסמן למחיקה
> 
>     2. מכניס סיבה למחיקה (לפי משוב מעדי)
> 
>     3. השירות עובר לסטטוס ״מומלץ למחיקה״ (מופיע בטקסט אפור במסך הראשי, ו/או תחת רשימה נפרדת של מחוקים)
> 
>     4. משתמש ברמת אדמין יכול למחוק לגמרי

נלך עם זה

**Comment by niryariv** [comment]
כשהשירות במצב מחוק (אבל ניתן לשחזור) צריך שכל התיבה שלו בדף השירותים תופיע באפור, לא רק הטקסט ״מחוק״ - כדי להדגיש את המצב ולהקטין את הסכוי לבלבול
