### ISSUE TITLE
ברמת הרשאות עריכה, משרד לא מופיע בדף שרותים חברתיים

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#30]
1. משתמשת ממשרד הבריאה נכנסת עם הרשאות ״עריכה״ מקבלת את הדף הבא:
![image](https://user-images.githubusercontent.com/1771/105980933-26622e80-609e-11eb-9614-d2246caf5a81.png)

2. עם הרשאות ״ניהול״, השרותים של המשרד מופיעים:
![image](https://user-images.githubusercontent.com/1771/105980984-367a0e00-609e-11eb-83bd-52d54fdf73fe.png)

**Comment by akariv** [comment]
Fixed via dataspot/dgp-app@f7ae15c6e9ff54f4d81dda6567183473506cfcee
