### ISSUE TITLE
להוסיף רווח בין ״שמירת/מחיקת״ ל״איש קשר״

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#31]
https://data-input.obudget.org/he/datarecords/contact/bnymyn-ntnyhv

![Screen Shot 2021-01-28 at 15 14 59](https://user-images.githubusercontent.com/1771/106143538-98f50c00-617b-11eb-862f-b21afb0608ae.png)

**Comment by niryariv** [comment]
לא רואה שינוי אצלי.. צריך לבצע איזה מחיקת קש בשרת?

![Screen Shot 2021-03-08 at 19 45 47](https://user-images.githubusercontent.com/1771/110360046-e56b1b80-8046-11eb-98a3-32608b272c8e.png)

**Comment by akariv** [comment]
זה עוד לא על השרת

**Comment by akariv** [comment]
עכשיו על השרת
