### ISSUE TITLE
הוספת חיווי ״לא נמצאו מכרזים / מפעילים״

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#35]
כיום כאשר לא נמצאו מפעילים או מכרזים משוייכים לתקנה מסוימת, הממשק נראה כך:
![Screen Shot 2021-01-28 at 16 09 25](https://user-images.githubusercontent.com/1771/106149731-44ee2580-6183-11eb-97c0-9c19e63da742.png)

צריך להוסיף טקסט תחת הלשונית, ״לא נמצאו מכרזים״ (או מפעילים) כדי לתת חיווי ברור שאין מידע, וזו לא תקלה כלשהי בהצגת התוכן

**Comment by niryariv** [comment]
זה יושם? נראה שפשוט מופיע ריק
https://data-input.obudget.org/he/datarecords/social_service/tknyt-hknh-ltsh-l-tknyt-lkhyylym-bvddym
![Screen Shot 2021-04-14 at 15 07 05](https://user-images.githubusercontent.com/1771/114707597-166bf980-9d33-11eb-933e-6b8a54c00a6e.png)

**Comment by akariv** [comment]
זה נראה לי מיותר אחרי שיש את האפשרות לחפש מכרז ולהוסיף אותו ידנית.

**Comment by niryariv** [comment]
יכול להיות שלא הבנתי את התהליך.

המחשבה שלי היא שמשתמש מחפש תקנה ומקבל את המכרזים/מפעילים הקשורים. אבל יכול להיות שהמשתמש בחר תקנה שאין לה מכרזים/מפעילים, ואז אנחנו רוצים לתת חיווי לגבי זה שכנראה בחר תקנה לא נכונה - למנוע מצב שהוא מתחיל לחבר ידנית מכרזים ומפעילים שלא קשורים

**Comment by akariv** [comment]
אני מעריך שכמות הטעויות בבחירת תקנה לא יהיו גדולות - שם התקנה הוא מאוד
אינדיקטיבי. מצד שני, הקשר בין בחירת התקנות להופעת המכרזים/מפעילים המוצעים
אינו אינטואיטיבי.

יכול להיות שאפשר להוסיף הודעה יותר מדויקת כגון:
- ״על מנת להציג הצעות למפעילים קשורים יש לשייך תקנות תקציביות לשירות״ (אם
לא נבחרו תקנות)
- ״לא נמצאו הצעות למפעילים קשורים על סמך התקנות התקציביות שנבחרו״ (אם כן
נבחרו תקנות)

אבל לא בטוח אם זה יועיל או יבלבל יותר.

**Comment by niryariv** [comment]
אולי משהו כמו ״לא נמצאו במערכת מכרזים המשויכים לתקנה 1.2.3.4 - ניתן להוסיף ידנית מכרזים כאן:״? 

יכול להיות שעדיף באמת לראות קודם כל את השימוש. משרדי החינוך והבריאות אמורים לעבוד על ההזנה השבוע, אבדוק מולם
