### ISSUE TITLE
להוסיף הסבר לגבי השדות למילוי

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#37]
ליד כל שדה רלוונטי, איקון סימן שאלה, בלחיצה/מעבר על האיקון נפתחת תיבת טקסט עם הסבר לגבי השדה

@ShiraTza הוסיפי כאן בבקשה רשימת שדות וטקסט לשדה (אפשר בקישור לגליון גוגל)

**Comment by niryariv** [comment]
@akariv רשימת שדות והסברים [כאן](https://drive.google.com/file/d/1iEE8L0SB1DblmF9VEOI8GVT4rkOIwl8D/view?usp=sharing)

**Comment by ShiraTza** [comment]
היי
שימו לב שזהו נוסח לא סופי של ההסברים

תודה

‫בתאריך יום ד׳, 10 בפבר׳ 2021 ב-17:59 מאת ‪Nir Yariv‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by akariv** [comment]
ok, תעדכני בבקשה כשהנוסח סופי

**Comment by niryariv** [comment]
מעביר לבקלוג עד לנוסח סופי

**Comment by niryariv** [comment]
@ShiraTza מעביר את המשימה אלייך, לייצר נוסח סופי להסברים

**Comment by niryariv** [comment]
[נוסח סופי כאן](https://drive.google.com/file/d/1jFi8b-O1I_dzmi-nt_jMWvn3B949A0Au/view?usp=sharing)
