### ISSUE TITLE
הוספת שדה: קבצים רלוונטים

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#38]
מאפשר להעלות קבצים שמשויכים לשירות חברתי (למשל חוזי התקשרות). הקבצים שעולים פומביים וזמינים לכל משתמש

**Comment by niryariv** [comment]
הרעיון הוא לאפשר הזנת קישור למסמך, לא העלאת המסמך עצמו.

אדם בודק מול דאטה.גוב אפשרות להשתמש באתר לאחסון מסמכים אם צריך

**Comment by akariv** [comment]
@emrib נראה לי שאפשר לסגור?
