### ISSUE TITLE
הוספת חיווי למכרז שכבר קושר לשירות אחר

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#41]
כאשר הממשק מציג מכרז שכבר קושר לשירות חברתי אחר, להוסיף אייקון ליד המכרז, בלחיצה/מעבר פותח תיבת טקסט ״המכרז קושר לשירות[ים]:״ עם רשימת השירותים שקושרו

**Comment by morchickit** [comment]
@akariv - כמה נפוץ זה?

**Comment by akariv** [comment]
תיאורטית לא אמור להיות קיים בכלל

**Comment by morchickit** [comment]
אז שנסגור לבינתיים? 
@ShiraTza - יש לך דוגמא לה?

**Comment by ShiraTza** [comment]
היי
האמת שלא נתקלנו בדבר הזה, בינתיים לשים בצד

‫בתאריך יום ג׳, 28 ביוני 2022 ב-12:19 מאת ‪morchickit‬‏ <‪
***@***.***‬‏>:‬
