### ISSUE TITLE
ייבוא מידע ממשרד הרווחה

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#42]
את המידע ממשרד הרווחה אנחנו רוצים לייבא אוטומטית, מקובץ שיכיל את כל הסעיפים הרלבנטים מקטלוג השרותים של המשרד + כל השדות שאנחנו מבקשים לכל סעיף (תקציב, מוטבים, והשדות החדשים).

כל זה כשאנחנו שמים בצד כרגע את החבור למכרזים וספקים, שיטופל בנפרד

@akariv צריך לייצר גליון עם הפורמט שאנחנו מבקשים לייבא. אני מניח שזה פשוט גליון עם כל השדות שיש לנו כיום בממשק הזנה - משהו נוסף שצריך לשים לב אליו או שאני יכול להתקדם ולייצר את הגליון?

**Comment by akariv** [comment]
שיהיה באותו הפורמט של ספר השירותים הנוכחי.

**Comment by niryariv** [comment]
פלוס השדות החדשים (קבוצת גיל, קהל יעד וכו) או בדיוק אותו פורמט?

**Comment by niryariv** [comment]
קובץ לייבוא [כאן](https://drive.google.com/file/d/1802mjve-z2C7_GfgY_O1aYV3IiZ0eV6c/view?usp=sharing)

בקובץ יש שני שדות לתאור השירות, שדה ״השירות״ ושדה ״תיאור השירות״. בייבוא צריך למזג אותם לשדה אחד, כשהתוכן ב״השירות״ הוא פסקה ראשונה והתוכן מ״תיאור השירות״ בהמשך
