### ISSUE TITLE
לאפשר ביטול הרשאות משתמש / שיוך למשרד

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#43]
כיום, מרגע שמשתמש שויך למשרד אין אפשרות לבטל שיוך, אלא רק לשייך אותו למשרד אחר / כל המשרדים
![Screen Shot 2021-02-02 at 14 40 22](https://user-images.githubusercontent.com/1771/106601676-9a03b000-6564-11eb-8df8-cfc4fe0518aa.png)

מבקש אפשרות של שדה ריק בבחירה, כדי להחזיר משתמש למצב שאינו משויך לאף משרד

כנ״ל לגבי הרשאות:
![Screen Shot 2021-02-02 at 14 41 29](https://user-images.githubusercontent.com/1771/106601806-c0c1e680-6564-11eb-96a8-f51bddbf8b8c.png)

**Comment by akariv** [comment]
אפשר להעביר משתמש לצפיה בלבד כדי שלא תהיה לו הרשאה לשום משרד.
אם רוצים למחוק משתמש לגמרי, אפשר לעשות זאת.
