### ISSUE TITLE
הוספת שדות: סוג מכרז

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#47]
1. פומבי | פטור ממכרז
2. (מתוך הרשימה ב #50) אם פטור, שדה בחירה לסיבת הפטור 
3. אם פומבי, שדה בחירה לסוג, מתוך האפשרויות: סגור, מסגרת, מאגר

**Comment by niryariv** [comment]
ליישם סיבות פטור מתוך [הרשימה](https://drive.google.com/file/d/1IzzE6GLyCZAOVU01bOr9ncAIgjlRNmFf/view?usp=sharing)

**Comment by akariv** [comment]
זה כבר עשוי. @niryariv
