### ISSUE TITLE
הוספת שדה: פריסה גאוגרפית

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#49]
1. צפון | מרכז | דרום | ירושלים 
2. אפשרות ליותר מערך אחד

**Comment by akariv** [comment]
@niryariv 
לאן השדה הזה אמור להיות מחובר? לרמת השירות? המפעיל?

**Comment by niryariv** [comment]
שירות

**Comment by akariv** [comment]
יש שירותים שניתנים לא בכל הארץ? יש דוגמה לשירות כזה?

**Comment by niryariv** [comment]
אתה צודק - מפעיל, בהקשר של השירות/מכרז הספציפי

**Comment by akariv** [comment]
אוקיי, אז זה קיים כבר. הדרישה הנוספת היא שיהיה אפשר לסמן מספר אפשרויות?

**Comment by niryariv** [comment]
כן
