### ISSUE TITLE
budget items are x1000 actual cost

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#5]
![Screen Shot 2020-08-30 at 10 16 07](https://user-images.githubusercontent.com/1771/91653467-e0cb1680-eaa9-11ea-91d3-be969b6688de.png)

![Screen Shot 2020-08-30 at 10 16 51](https://user-images.githubusercontent.com/1771/91653475-f50f1380-eaa9-11ea-88a7-102e275a2db8.png)

**Comment by akariv** [comment]
This is a problem with the raw data:

<img width="727" alt="Screen Shot 2020-08-30 at 13 35 47" src="https://user-images.githubusercontent.com/265333/91656952-d0c13000-eac5-11ea-8b88-56e56336bc14.png">

We'll probably need to do manual review of these files and fix any errors we find.

How do you propose to proceed with that?

**Comment by niryariv** [comment]
I'll fix manually if needed. But something's weird here - both Numbers and Google Sheets display the # as 62,634, while storing the actual 62634000 value. I assume it's some Excel formatting feature. 

@akariv did you x1000 the data during the import? If so it seems to me we can just reimport without it and get the correct values.

**Comment by akariv** [comment]
The title says thousands of nis, so it's best if the data is correct.
The relevant file is in git (I'm not using the exported google docs). I'll fix this file now but please check to see if there are any other similar problems.

**Comment by niryariv** [comment]
I rechecked the original files. 

It seems like Klita 2016 is the only one that uses this formatting method. Where normally a value of "1000 nis" would be represented as a value of "1" in the spreadsheet, in this specific file alone it's formatted to display as "1" but the actual value is "1000".

So, applying x1000 during import makes sense everywhere but this file.

I can manually fix the Klita 2016 sheet, but since I don't have Excel it might cause the exporting issues that made us use the original xls files. Can you reimport this file only, without x1000? If not, I'll fix manually and send as csv.

**Comment by akariv** [comment]
Yes, l have excel and I'll fix the file, np

**Comment by akariv** [comment]
Done
