### ISSUE TITLE
שינויים לשדה ״סוג מכרז״

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#54]
(בהמשך ל #47)

1. אם פטור, לא להציג רשימת בחירה (סיבת הפטור מופיעה תחת ״תקנה״)
2. אם פומבי, להציג רשימת בחירה: סגור | מסגרת | מאגר (להוריד ״לא רלוונטי״ מהרשימה)

**Comment by niryariv** [comment]
רשימת בחירה/המרה לסוגי פטורים [כאן](https://drive.google.com/file/d/1FU04BKTBcgW5P5SrMByMiXufVQgYnoFW/view?usp=sharing)

**Comment by akariv** [comment]
גם זה כבר עשוי @niryariv

**Comment by niryariv** [comment]
כולל [טבלת ההמרה](https://drive.google.com/file/d/1FU04BKTBcgW5P5SrMByMiXufVQgYnoFW/view?usp=sharing) וביטול האפשרות ל״לא רלוונטי״ במכרז פומבי?

**Comment by akariv** [comment]
כפי שאמרנו, טבלת ההמרה לא רלוונטית למערכת ההזנה אלא רק לתצוגה.
