### ISSUE TITLE
דף שער לרכש חברתי

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#6]
חשבתי על משהו בסגנון הדף הקיים כאן, כשכל אלמנט הוא משרד אחר. מה דעתך על הכיוון?

![Screen Shot 2020-08-30 at 11 44 22](https://user-images.githubusercontent.com/1771/91654999-2d1c5380-eab6-11ea-8edc-729cb538d550.png)

**Comment by akariv** [comment]
I would _prefer_ if we created a custom, redesigned page to replace this one, and not create a very special landing page for this - 
https://next.obudget.org/i/budget/C2/2019

As for the design, let's try to answer first (to ourselves) what are the most important pieces of information we'd like to provide the users that arrive here?

**Comment by niryariv** [comment]
(מערבב עברית ואנגלית לפי הנוחות כאן, אם אתה מעדיף שפה אחת תגיד לי, אין בעיה מבחינתי)

הוגדרו לנו שלושה סוגי משתמשים: ממשלתי, ספק שירות, ציבור רחב. אני כרגע מתמקד על הממשלתי (כי שם הלקוח המיידי) והציבור הרחב (כי קל לי יותר להעריך צרכים, בהיותי אחד ממנו)

השאלות שאני חושב שהעמוד הראשי צריך לענות עליהן (לפי השקף המצ״ב ממצגת הפרויקט + פורמט ספר הרכש + שכל ישר, בשאיפה):

1. מה האתר הזה, מהם שירותים חברתיים וכו׳ (פחות רלבנטי כרגע, בהמשך נוסיף קופי שיענה על זה)

2. מה סך התקציב שהמדינה מוציאה על שירותים חברתיים במיקור חוץ, מה מספר המוטבים (על פניו בעייתי לחשב, צריך לבדוק איך הם הגיעו למספר שלהם), איך הנ״ל משתנים לאורך השנים

3.  איך התקציב מתחלק, ומכאן לחפור בהיררכיה עד שמגיעים לדף פרטי שירות ספציפי

נדמה לי שאני מבין לאן אתה מכוון - יותר מעניין מבחינת המשתמש הציבורי לנתח על פי אוכלוסיה או שירות (״סיוע לעולים חדשים״, ״פגועי נפש״) מאשר לפי משרד ממשלתי. יש לנו אפשרות כרגע לבצע את האיגוד הזה בין כמה משרדים?
