### ISSUE TITLE
אחרי שהוספתי מפעיל, לא יכול להוסיף אחרים או לערוך פרטים

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#66]
1. בחרתי מפעיל דרך ״חיפוש והוספה״ בלשונית מפעילים
2. המפעיל מוצג מיידית כמקושר
3. לא מוצא דרך לערוך פרטים או לבטל את הקישור
4. לחיצה על ״חיפוש והוספה״ (בלשונית הזו וגם באחרות) פותחת מודאל ריק

**Comment by akariv** [comment]
בחירה דרך החיפוש של מפעיל או מכרז תמיד תוסיף אותו כמקושר (אין סיבה לעשות אחרת)
שאר הנושאים טופלו.

**Comment by niryariv** [comment]
להציג אותו כמקושר זו התנהגות נכונה, הכוונה שלי שאין לי דרך לבטל את הקישור במקרה שהתברר לי אח״כ שזו היתה טעות
(יכול להיות שתוקן אבל עוד לא באתר?)

![Screen Shot 2021-04-21 at 9 35 50](https://user-images.githubusercontent.com/1771/115507566-f84b4f80-a284-11eb-96b6-e2f04776c57a.png)

**Comment by niryariv** [comment]
היה אצלי בקש, תקין אחרי ריפרוש

**Comment by akariv** [comment]
בשביל כבוד אתה צריך לרפרש את הקש

**Comment by niryariv** [comment]
העולם הזה גורם לי / לרפרש את הקש
