### ISSUE TITLE
מחיקה מהירה יותר של תקנות מקושרות

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#67]
מקרה לדוגמא:

1. בחרתי בטעות תקנה לא רלבנטית
2. אני רוצה למחוק את הקישור, אבל במקום זה אני צריך למחוק שנה אחר שנה
3. יש הרבה שנים.. וכל מחיקה של שנה מלווה בדיאלוג ״אשר|בטל״

פתרון:
1. מעל הרשימה השנתית, להציג רשימה של תקנות מקושרות כפי שמופיעות בממשק החיפוש (שם + שנים)
2. לאפשר מחיקה של תקנה ברשימה הזו, וכך למחוק את כל השנים הרלבנטיות אוטומטית
3. אני לא מכיר מספיק את נושא התקציב - האם אפשר פשוט לסנן תקנות שלא מתאימות לשנים שאנחנו מדברים עליהן או להראות אותן בצורה שמזהירה שהן פגו תוקף לפני 2015 נניח? יכול לסייע במניעת הטעויות

**Comment by akariv** [comment]
לא חושב שזה תרחיש מספיק שכיח ששוה להשקיע בו (ועל הדרך לסבך את ממשק המשתמש
באיזור שגם ככה לא פשוט למשתמשים).
אגב, למה למחוק תקנות ישנות? אם יש תקנה שהולכת אחורה (לפני 2015), אז הרווחנו
עוד מידע היסטורי על השירות.
בחיפוש עצמו מופיע טווח השנים של התקנה - עוזר למצוא את התקנה הרלוונטית
(למרות שאני מאמין שבסופו של דבר בד״כ פשוט יזינו את מספר התקנה ישירות כך שלא
יהיו טעויות).

**Comment by niryariv** [comment]
אני אנסה לקבל משוב ממנהלות הרכש לגבי התהליך - אם מספרי התקנות בד״כ ידועים מראש

לדעתי בכל מקרה יש טעם לפשט את התהליך של מחיקת תקנות מקושרות, הסיכוי לטעות עדיין קיים וכרגע התיקון יכול להיות מייגע

**Comment by akariv** [comment]
אוקיי, אני אזיז את זה לעמודה אחרת עד לקבלת משוב משתמשים

**Comment by niryariv** [comment]
הרגע התקשרה אושרת לדווח שזה בדיוק מה שקרה לה עכשיו :) עדכנתי את #108 כך שיענה גם על זה (יוצגו רק שורות של 2017 והלאה, כך שהמחיקה תהיה פחות מתישה)
