### ISSUE TITLE
מציאת מפעילים קשורים

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#69]
1. חיברתי מכרז לשירות
2. סימנתי כקשור
3. מצפה לראות רשימת מפעילים רלבנטים, בפועל לשונית ״מפעילים״ ריקה - להבנתי אמור להיות [זה](https://next.obudget.org/i/org/association/580007102)?

(אני מנסה למצוא את הפרטים באתר מפתח התקציב אבל נראה שכל חיפוש מתוך דף פנימי מוביל אותי לדף ריק כאן:
https://next.obudget.org/s/ )

**Comment by akariv** [comment]
איזה שירות? איזה מכרז? 
אם חיברת מכרז שהגעת אליו דרך החיפוש, אז לא יופיעו מפעילים כי (כנראה) לא היה לנו מידע על התקשרויות רלוונטיות
