### ISSUE TITLE
במצב של פטור ממכרז לא להציג שדות ״מודל תמחור״ ו״סוג מכרז״

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#72]
האם יש לנו דרך לדעת כיום אם המכרז הוא בפטור? אם לא, אני מניח שצריך להוסיף צ׳קבוקס של ״פטור ממכרז״

**Comment by akariv** [comment]
<img width="1192" alt="Screen Shot 2021-04-29 at 13 21 27" src="https://user-images.githubusercontent.com/265333/116536775-02f18e80-a8ee-11eb-8a0e-b0491ce969a8.png">

**Comment by niryariv** [comment]
מטופל ב #78
