### ISSUE TITLE
חיפוש שירות

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#73]
תיבת חיפוש בדף לוח בקרה שמאפשרת לחפש שירות לפי טקסט (משווה מול שם שירות + תיאור שירות)

**Comment by niryariv** [comment]
התוצאה כרגע היא שנפתחים כל השירותים שמילת החיפוש קיימת בהם, אבל לא ניתן לראות את שאר השירותים עד שמבטלים את החיפוש. צריך לאפשר למשתמשת להמשיך לפתוח את הרשימה, גם לשירותים שלא תואמים את החיפוש.

**Comment by akariv** [comment]
זה לא ממש הגיוני - אם ביחידה מסוימת יש 20 שירותים אז צריך להציג את כולם גם
אם רק אחד מהם מתאים לחיפוש?

**Comment by niryariv** [comment]
לא, הכוונה שלי שהתוצאה תהיה בדיוק כמו שהיא היום, אבל המשתמש יוכל, לאחר
שחיפש, לנווט ידנית בהיררכיה. אני מבין שהבעיה שנוצרת היא שאז יוצגו כל
השירותים שנמצאים באותו מקום בהיררכיה עם שירות שנמצא בחיפוש. אפשר להתגבר על
זה אם נצבע את אלו שתואמים לחיפוש בצבע רקע אחר. מה דעתך?

**Comment by akariv** [comment]
שזה יהיה פחות נוח (יהיה צריך לגלול בשביל למצוא את התוצאות) אבל זה לא מאוד
אכפת לי.

**Comment by niryariv** [comment]
אוקי, להערכתי זה מתקזז עם חוסר הנוחות של המשתמשים שייתקעו במוד של תוצאות חיפוש ולא יבינו למה לא מוצאים שירות מסוים :)
