### ISSUE TITLE
למיין טבלת תקנה תקציבית לפי סדר יורד של שנים

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#75]
כלומר להפוך את הסדר שבו הטבלה הזו מוצגת:

![Screen Shot 2021-04-29 at 19 26 53](https://user-images.githubusercontent.com/1771/116585253-dc991680-a920-11eb-85a6-a917c4f15ef3.png)

**Comment by niryariv** [comment]
כנ״ל לגבי טבלת תקציב מאושר כמובן

**Comment by akariv** [comment]
נסגר בטעות

**Comment by niryariv** [comment]
רואה את התיקון רק בטבלת תקציב מאושר
![Screen Shot 2021-05-11 at 13 07 35](https://user-images.githubusercontent.com/1771/117798482-e04e6680-b259-11eb-8ccd-50497b415e1a.png)
