### ISSUE TITLE
שינויים לאלמנט תקציב מאושר

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#76]
1. לשנות כותרת ל״תקציב ביצוע בפועל״
2. להשתמש רק בנתוני התקשרויות, לא נתונים מתוך דוח החשב (מכיון שדוח החשב מכיל את כלל ההוצאה על התקנה ואנחנו רוצים להסתמך על תשלומים שהועברו בפועל למכרזים הרלבנטים בלבד)

![Screen Shot 2021-04-29 at 19 49 54](https://user-images.githubusercontent.com/1771/116588323-128bca00-a924-11eb-9db9-7dede5d4792c.png)

**Comment by akariv** [comment]
1. התקשרויות לא מחוברות לשנה תקציבית ואין דרך לדעת כמה כסף יצא בשנה מסוימת.
2. המטרה של הצגת המידע ב**מערכת ההזנה** היא לוודא שהתקנה התקציבית שהוזנה
היא התקנה הנכונה (כולל האחוזים הנכונים) על ידי זה שמוודאים שהתקציב והביצוע
תואמים את מה שמצופה.

**Comment by niryariv** [comment]
שירה בודקת

**Comment by niryariv** [comment]
תשובה משירה: 

במידה ותקציב השירות הוא 100% מתקציב התקנה - להביא את הנתון מדוח הביצוע.
במידה ולא - לתת למשרדים מקום לערוך/להזין ידנית את ביצוע התקציב בפועל.

**Comment by akariv** [comment]
המשרדים כלל לא יודעים מה הביצוע השנתי גם ככה... נוסיף את זה לפול של הדרישות
החדשות שמחוץ ל-scope.

**Comment by niryariv** [comment]
לטענת יוני הם יודעים (או צריכים לדעת..) מבקשים להשאיר את זה כשדה חובה למילוי

**Comment by niryariv** [comment]
@akariv איפה אנחנו עומדים לגבי זה? שנשים ברשימת הדברים לברר עם שירה?

**Comment by akariv** [comment]
נראה לי שכדאי

**Comment by niryariv** [comment]
ממשיך ב #97
