### ISSUE TITLE
שינויים לממשק חיפוש מכרזים/מפעילים

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#78]
1. סידור הרשימה לפי משרדים ולפי תאריכים - העדכני למעלה
2. אופציה לסימון מרובה של כמה מכרזים/מפעילים במקביל
3. הצעה של מכרזים שכנראה קשורים - ברגע שמסמנים מכרז, שיופיעו בעמוד המכרזים כל ההתקשרויות - מכרזים ופטורים שהמערכת מזהה כקשורים לאותו המכרז (על פי חיפוש שמי) 

(אין צורך לסנן כוונות להתקשרות, הורדנו את השינוי הזה)

**Comment by akariv** [comment]
הרשימה מסוננת לפי משרדים.
הסינון הוא לפי הרלוונטיות לחיפוש - כל מיון אחר יתן תוצאות חיפוש פחות טובות
אפשר לבחור כמה מכרזים מתוך אותו מסך החיפוש.
את (3) אמרנו שנעשה כשתהיה הגדרה יותר טובה של מה שרוצים
