### ISSUE TITLE
ממשק עריכה - חיבור שירות לתקנה תקציבית

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#8]
@akariv - להלן הצעת ממשק

![service-takana](https://user-images.githubusercontent.com/1771/93880290-e81ac400-fce5-11ea-9f82-b16daf9c497a.png)

**Comment by akariv** [comment]
אני מעדיף לא לסבך את ממשק המשתמש של מפתח התקציב עצמו אלא לייצר ממשק ייעודי לעניין.

הנה מוקאפ @niryariv 

![IMG_20200923_093930.jpg](https://user-images.githubusercontent.com/265333/93976070-13062600-fd81-11ea-976c-f834357d494c.jpg)

![IMG_20200923_093945.jpg](https://user-images.githubusercontent.com/265333/93976087-1ac5ca80-fd81-11ea-8caf-85b7d99d485c.jpg)

**Comment by niryariv** [comment]
זה לא אותו דבר בגדול? :)

בעקרון בתפיסה שלי יש שני מצבים לדף פרטי שירות:

1. שירות שטרם קושר לתקנה - ואז מציגים פרטים בסיסיים ואם למשתמש יש הרשאת עריכה גם ממשק קישור לתקנה

2. שירות שקושר לתקנה - ואז מציגים את כל המידע שנגזר מכך, ואם יש הרשאת עריכה גם ממשק להסרת מה שלא קשור

**Comment by akariv** [comment]
בגדול ברור, זה אותו התהליך.

ההבדל הוא רק בכך שאנחנו עושים ממשק משתמש ייעודי ולא מתלבשים על מפתח התקציב

**Comment by niryariv** [comment]
כן, ברור. זה יקבל ממשק משלו. הלכתי עם מה שעשית עד עכשיו פשוט כי חשבתי שיהיה הכי נוח לממש.

בגישה הזו ממשק ההזנה בעצם מאוחד עם ממשק הצפיה - שאותו נרצה לבנות עם מעצב ולאשר מול הלקוח לפני שמיישמים. אז אני תופס את זה כפתרון ביניים עד שנבנה עיצוב לממשק האמיתי. נשמע הגיוני? זמין לדבר אם תרצה
