### ISSUE TITLE
פטורים מוצגים כמכרז (?)

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#81]
https://data-input.obudget.org/he/datarecords/social_service/typvl-bn-rvt-bsykvn-bmvsdvt-hkhm-d

![Screen Shot 2021-05-05 at 9 21 46](https://user-images.githubusercontent.com/1771/117103642-657ddb00-ad83-11eb-93ee-b0827531cebe.png)

**Comment by akariv** [comment]
Resolved in version 1.0.14 (deploying now)
