### ISSUE TITLE
בטבלת מכרזים לאפשר עריכה של שדה תוקף (ושאר השדות ברי העריכה) גם אחרי שהמשתמש שמר את הדף

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#83]

**Comment by akariv** [comment]
תוקף עבור מכרזים אפשר לערוך תמיד.
עבור פטורים השדה אינו ניתן לעריכה.

**Comment by niryariv** [comment]
אחלה. אגב יש איזה שרת סטייגי׳נג שאפשר לבדוק עליו דברים כאלה, שכוללים שמירה של תוכן? (או שפשוט בודקים בשירותים של משרד הרווחה :)

**Comment by akariv** [comment]
כרע אין סטייגינג... אפשר לייצר כזה שרת אם רוצים.
