### ISSUE TITLE
איפשור שמירה ללא הגדרת היחידה

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#86]
1. פותח שירות ״[ייעוץ וניהול אספקת שירותים עבור נכי גפיים](https://data-input.obudget.org/he/datarecords/social_service/yy-vts-vnyhvl-spqt-shyrvtym-bvr-nky-gpyym)״
2. השירות מוגדר תחת אגף שיקום, כששם היחידה ריק (מנהלת הרכש מאשרת שזה הסיווג הנכון)
3. לוחץ על ״שמירה וסימון כהושלם״
4. הודעת שגיאה ״יש למלא ערכים בכל השדות המסומנים!״ מתייחסת לשם היחידה

![Screen Shot 2021-05-11 at 12 35 58](https://user-images.githubusercontent.com/1771/117794375-db87b380-b255-11eb-848e-3d3a84854703.png)

**Comment by akariv** [comment]
אפשר לעדכן את המבנה הארגוני במסך המבנה הארגוני:

<img width="1178" alt="Screen Shot 2021-05-11 at 12 46 19" src="https://user-images.githubusercontent.com/265333/117795551-f870b680-b256-11eb-9246-6d050344a7a2.png">

אם אין רמת היררכיה שלישית, אפשר להסיר אותה.

**Comment by niryariv** [comment]
רמת היחידה קיימת, אבל חלק מהשרותים כפופים ישירות לאגף. לדוגמא:

![Screen Shot 2021-05-11 at 12 49 56](https://user-images.githubusercontent.com/1771/117796068-67e6a600-b257-11eb-8b61-4c465ea0c527.png)
