### ISSUE TITLE
לאפשר סיום עבודה בלי מילוי מידע על מכרזים לא קשורים

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#89]
[לדוגמא כאן](https://data-input.obudget.org/he/datarecords/social_service/yy-vts-vnyhvl-spqt-shyrvtym-bvr-nky-gpyym)

![image](https://user-images.githubusercontent.com/1771/117819268-0ed83b80-b272-11eb-82c2-2ac86815cc39.png)

**Comment by akariv** [comment]
יכול להיות שירות שאין לו בכלל מכרזים?

**Comment by niryariv** [comment]
לא, חייב להיות לשירות מכרז אחרת הוא לא ניתן בפועל ולא צריך להיות במערכת (תשובה משירה)

**Comment by akariv** [comment]
אוקיי, עכשיו הבנתי מה העניין.
יטופל.

**Comment by niryariv** [comment]
(אני מניח שמובן מאליו אבל רק לוודא, פטור = מכרז לצורך הענין)
