### ISSUE TITLE
לאפשר מחיקה של מכרזים / מפעילים לא קשורים

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#90]
(יכול לייתר את #89)

**Comment by akariv** [comment]
לא מבין איך זה קשור ל-#89?

**Comment by niryariv** [comment]
כי אז אפשר פשוט למחוק את המכרזים הלא קשורים ולא מקבלים הודעת שגיאה שלא הוזן מידע לגביהם :)
