### ISSUE TITLE
מפעילים לא מוצגים אחרי בחירת מכרז/פטור

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#93]
1. מחפש מכרזים ובוחר מכרז - למשל ״המשך התקשרות עם עמותת אנוש״
2. כצפוי המכרז מופיע ברשימה
3. רשימת מפעילים לא מתעדכנת - עמותת אנוש לא מופיעה שם

**Comment by akariv** [comment]
כיום הקישור בין מכרזים למפעילים מבוצע אך ורק דרך התקשרויות באותה התקנה.
ברווחה אין לנו התקשרויות, אז אין אפשרות לבצע את החיבור.

אמרנו שעבור פטורים כן יהיה אפשר לעשות משהו בנידון (כאשר יש להם מפעיל), אבל זה עדיין לא מומש.

**Comment by niryariv** [comment]
עד כמה מורכב לתת פתרון לגבי פטורים? ליצור משימה?

**Comment by akariv** [comment]
כן, אני אנסה לפתור את זה היום

**Comment by niryariv** [comment]
סוגר, המשך טיפול ב #94
