### ISSUE TITLE
להוסיף אופציית בחירה ״לא רלוונטי״ בשדה ״ניתן מכח״

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#95]
יש שירותים שהשדה לא רלוונטי אליהם - עקרונית אפשר להפוך אותו לאופציונלי, אבל אנחנו בוחרים בשיטה הזו כיוון שאנחנו רוצים לוודא שמזיני הנתונים שמים לב אליו

**Comment by akariv** [comment]
לא עדיף פשוט למחוק את השורה הריקה?

**Comment by niryariv** [comment]
כן, ״לא רלוונטי״ מחליף את השורה הריקה
