### ISSUE TITLE
קישור מכרז לא מביא ליבוא מפעילים פוטנציאלים לרשימה

### ISSUE THREAD

**Issue by niryariv** [hasadna/social-procurement#98]
1. https://data-input.obudget.org/he/datarecords/social_service/rkysht-qvdym-grytryym
2. מחוברים מספר מכרזי ״קודים גריאטרים״
3. אין מפעילים מוצעים

**Comment by akariv** [comment]
המכרז הזה עדיין פתוח, אין לו מפעילים:

https://mr.gov.il/ilgstorefront/he/p/622043

**Comment by niryariv** [comment]
אבל ברשימה גם מכרזים משנים קודמות:
![Screen Shot 2021-05-13 at 17 57 05](https://user-images.githubusercontent.com/1771/118144078-b2f9e800-b414-11eb-8ff1-7b3f4b2797f0.png)

**Comment by akariv** [comment]
נכון - מצאתי שם בעיה, מעלה פתרון בדקות הקרובות.

**Comment by niryariv** [comment]
מופיעים 41 מפעילים פוטנציאלים, לטענת סימה אמורים להיות 213

**Comment by akariv** [comment]
המפעילים מגיעים מתוך דוחות ההתקשרות, אין לי מה לעשות אם הם לא מופיעים או
שלא מקושרים לתקנה הספציפית.

**Comment by akariv** [comment]
בכל מקרה סך ההתקשרויות בתקנה הזו נמוך באופן משמעותי מהתקציב שלה, מה שאומר
שיש הרבה התקשרויות חסרות - בדומה למצב ברווחה.

**Comment by niryariv** [comment]
cc @ShiraTza

**Comment by ShiraTza** [comment]
היי,

האם היה בירור לגבי זה? האם יש תשובה למה לא היה ייבוא של מפעילים
פוטנציאליים?

‫בתאריך יום ג׳, 18 במאי 2021 ב-10:43 מאת ‪Nir Yariv‬‏ <‪
***@***.***‬‏>:‬
